cjson_add.c
cJSON_Hooks failing_hooks
Referenced by cjson_add_array_should_fail_on_allocation_failure, cjson_add_bool_should_fail_on_allocation_failure, cjson_add_false_should_fail_on_allocation_failure, cjson_add_null_should_fail_on_allocation_failure, cjson_add_number_should_fail_on_allocation_failure, cjson_add_object_should_fail_on_allocation_failure, cjson_add_raw_should_fail_on_allocation_failure, cjson_add_string_should_fail_on_allocation_failure, cjson_add_true_should_fail_on_allocation_failure, cjson_create_double_array_should_fail_on_allocation_failure, cjson_create_float_array_should_fail_on_allocation_failure, cjson_create_int_array_should_fail_on_allocation_failure, cjson_create_string_array_should_fail_on_allocation_failure.
static void* failing_malloc(size_t size)
static void normal_free(void *pointer)
static void cjson_add_null_should_add_null(void)
References cJSON_AddNullToObject, cJSON_CreateObject, cJSON_Delete, cJSON_GetObjectItemCaseSensitive, cJSON::type.
Referenced by main.
static void cjson_add_null_should_fail_with_null_pointers(void)
References cJSON_AddNullToObject, cJSON_CreateObject, cJSON_Delete.
Referenced by main.
static void cjson_add_null_should_fail_on_allocation_failure(void)
References cJSON_AddNullToObject, cJSON_CreateObject, cJSON_Delete, cJSON_InitHooks, failing_hooks.
Referenced by main.
static void cjson_add_true_should_add_true(void)
References cJSON_AddTrueToObject, cJSON_CreateObject, cJSON_Delete, cJSON_GetObjectItemCaseSensitive, cJSON::type.
Referenced by main.
static void cjson_add_true_should_fail_with_null_pointers(void)
References cJSON_AddTrueToObject, cJSON_CreateObject, cJSON_Delete.
Referenced by main.
static void cjson_add_true_should_fail_on_allocation_failure(void)
References cJSON_AddTrueToObject, cJSON_CreateObject, cJSON_Delete, cJSON_InitHooks, failing_hooks.
Referenced by main.
static void cjson_create_int_array_should_fail_on_allocation_failure(void)
References cJSON_CreateIntArray, cJSON_InitHooks, failing_hooks.
Referenced by main.
static void cjson_create_float_array_should_fail_on_allocation_failure(void)
References cJSON_CreateFloatArray, cJSON_InitHooks, failing_hooks.
Referenced by main.
static void cjson_create_double_array_should_fail_on_allocation_failure(void)
References cJSON_CreateDoubleArray, cJSON_InitHooks, failing_hooks.
Referenced by main.
static void cjson_create_string_array_should_fail_on_allocation_failure(void)
References cJSON_CreateStringArray, cJSON_InitHooks, failing_hooks.
Referenced by main.
static void cjson_add_false_should_add_false(void)
References cJSON_AddFalseToObject, cJSON_CreateObject, cJSON_Delete, cJSON_GetObjectItemCaseSensitive, cJSON::type.
Referenced by main.
static void cjson_add_false_should_fail_with_null_pointers(void)
References cJSON_AddFalseToObject, cJSON_CreateObject, cJSON_Delete.
Referenced by main.
static void cjson_add_false_should_fail_on_allocation_failure(void)
References cJSON_AddFalseToObject, cJSON_CreateObject, cJSON_Delete, cJSON_InitHooks, failing_hooks.
Referenced by main.
static void cjson_add_bool_should_add_bool(void)
References cJSON_AddBoolToObject, cJSON_CreateObject, cJSON_Delete, cJSON_GetObjectItemCaseSensitive, cJSON::type.
Referenced by main.
static void cjson_add_bool_should_fail_with_null_pointers(void)
References cJSON_AddBoolToObject, cJSON_CreateObject, cJSON_Delete.
Referenced by main.
static void cjson_add_bool_should_fail_on_allocation_failure(void)
References cJSON_AddBoolToObject, cJSON_CreateObject, cJSON_Delete, cJSON_InitHooks, failing_hooks.
Referenced by main.
static void cjson_add_number_should_add_number(void)
References cJSON_AddNumberToObject, cJSON_CreateObject, cJSON_Delete, cJSON_GetObjectItemCaseSensitive, cJSON::type, cJSON::valuedouble, cJSON::valueint.
Referenced by main.
static void cjson_add_number_should_fail_with_null_pointers(void)
References cJSON_AddNumberToObject, cJSON_CreateObject, cJSON_Delete.
Referenced by main.
static void cjson_add_number_should_fail_on_allocation_failure(void)
References cJSON_AddNumberToObject, cJSON_CreateObject, cJSON_Delete, cJSON_InitHooks, failing_hooks.
Referenced by main.
static void cjson_add_string_should_add_string(void)
References cJSON_AddStringToObject, cJSON_CreateObject, cJSON_Delete, cJSON_GetObjectItemCaseSensitive, cJSON::type, cJSON::valuestring.
Referenced by main.
static void cjson_add_string_should_fail_with_null_pointers(void)
References cJSON_AddStringToObject, cJSON_CreateObject, cJSON_Delete.
Referenced by main.
static void cjson_add_string_should_fail_on_allocation_failure(void)
References cJSON_AddStringToObject, cJSON_CreateObject, cJSON_Delete, cJSON_InitHooks, failing_hooks.
Referenced by main.
static void cjson_add_raw_should_add_raw(void)
References cJSON_AddRawToObject, cJSON_CreateObject, cJSON_Delete, cJSON_GetObjectItemCaseSensitive, cJSON::type, cJSON::valuestring.
Referenced by main.
static void cjson_add_raw_should_fail_with_null_pointers(void)
References cJSON_AddRawToObject, cJSON_CreateObject, cJSON_Delete.
Referenced by main.
static void cjson_add_raw_should_fail_on_allocation_failure(void)
References cJSON_AddRawToObject, cJSON_CreateObject, cJSON_Delete, cJSON_InitHooks, failing_hooks.
Referenced by main.
static void cJSON_add_object_should_add_object(void)
References cJSON_AddObjectToObject, cJSON_CreateObject, cJSON_Delete, cJSON_GetObjectItemCaseSensitive, cJSON::type.
Referenced by main.
static void cjson_add_object_should_fail_with_null_pointers(void)
References cJSON_AddObjectToObject, cJSON_CreateObject, cJSON_Delete.
Referenced by main.
static void cjson_add_object_should_fail_on_allocation_failure(void)
References cJSON_AddObjectToObject, cJSON_CreateObject, cJSON_Delete, cJSON_InitHooks, failing_hooks.
Referenced by main.
static void cJSON_add_array_should_add_array(void)
References cJSON_AddArrayToObject, cJSON_CreateObject, cJSON_Delete, cJSON_GetObjectItemCaseSensitive, cJSON::type.
Referenced by main.
static void cjson_add_array_should_fail_with_null_pointers(void)
References cJSON_AddArrayToObject, cJSON_CreateObject, cJSON_Delete.
Referenced by main.
static void cjson_add_array_should_fail_on_allocation_failure(void)
References cJSON_AddArrayToObject, cJSON_CreateObject, cJSON_Delete, cJSON_InitHooks, failing_hooks.
Referenced by main.
int main(void)
References cJSON_add_array_should_add_array, cjson_add_array_should_fail_on_allocation_failure, cjson_add_array_should_fail_with_null_pointers, cjson_add_bool_should_add_bool, cjson_add_bool_should_fail_on_allocation_failure, cjson_add_bool_should_fail_with_null_pointers, cjson_add_false_should_add_false, cjson_add_false_should_fail_on_allocation_failure, cjson_add_false_should_fail_with_null_pointers, cjson_add_null_should_add_null, cjson_add_null_should_fail_on_allocation_failure, cjson_add_null_should_fail_with_null_pointers, cjson_add_number_should_add_number, cjson_add_number_should_fail_on_allocation_failure, cjson_add_number_should_fail_with_null_pointers, cJSON_add_object_should_add_object, cjson_add_object_should_fail_on_allocation_failure, cjson_add_object_should_fail_with_null_pointers, cjson_add_raw_should_add_raw, cjson_add_raw_should_fail_on_allocation_failure, cjson_add_raw_should_fail_with_null_pointers, cjson_add_string_should_add_string, cjson_add_string_should_fail_on_allocation_failure, cjson_add_string_should_fail_with_null_pointers, cjson_add_true_should_add_true, cjson_add_true_should_fail_on_allocation_failure, cjson_add_true_should_fail_with_null_pointers, cjson_create_double_array_should_fail_on_allocation_failure, cjson_create_float_array_should_fail_on_allocation_failure, cjson_create_int_array_should_fail_on_allocation_failure, cjson_create_string_array_should_fail_on_allocation_failure.