cJSON.c
true
false
isinf
isnan
NAN
internal_malloc
internal_free
internal_realloc
static_strlen
can_read
can_access_at_index
cannot_access_at_index
buffer_at_offset
cjson_min
typedef struct internal_hooks internal_hooks
error global_error
Referenced by cJSON_GetErrorPtr, cJSON_ParseWithLengthOpts.
internal_hooks global_hooks
Referenced by assert_not_array, assert_not_object, assert_not_parse_string, assert_parse_array, assert_parse_object, assert_parse_string, assert_parse_value, assert_print_array, assert_print_number, assert_print_object, assert_print_string, assert_print_value, cjson_add_item_to_object_should_not_use_after_free_when_string_is_aliased, cJSON_AddArrayToObject, cJSON_AddBoolToObject, cJSON_AddFalseToObject, cJSON_AddItemReferenceToArray, cJSON_AddItemReferenceToObject, cJSON_AddItemToObject, cJSON_AddItemToObjectCS, cJSON_AddNullToObject, cJSON_AddNumberToObject, cJSON_AddObjectToObject, cJSON_AddRawToObject, cJSON_AddStringToObject, cJSON_AddTrueToObject, cJSON_CreateArray, cJSON_CreateArrayReference, cJSON_CreateBool, cJSON_CreateFalse, cJSON_CreateNull, cJSON_CreateNumber, cJSON_CreateObject, cJSON_CreateObjectReference, cJSON_CreateRaw, cJSON_CreateString, cJSON_CreateStringReference, cJSON_CreateTrue, cJSON_Delete, cJSON_Duplicate, cJSON_free, cJSON_InitHooks, cJSON_malloc, cJSON_ParseWithLengthOpts, cJSON_Print, cJSON_PrintBuffered, cJSON_PrintPreallocated, cJSON_PrintUnformatted, cJSON_SetValuestring, replace_item_in_object, reset, skip_utf8_bom_should_not_skip_bom_if_not_at_beginning, skip_utf8_bom_should_skip_bom.
const char* cJSON_GetErrorPtr(void)
References global_error, error::json, error::position.
Referenced by file_test6_should_not_be_parsed, parse_with_opts_should_handle_empty_strings, parse_with_opts_should_handle_incomplete_json, supports_full_hd, test12_should_not_be_parsed.
char* cJSON_GetStringValue(const cJSON *const item)
References cJSON_IsString, cJSON::valuestring.
Referenced by cjson_get_string_value_should_get_a_string.
double cJSON_GetNumberValue(const cJSON *const item)
References cJSON_IsNumber, cJSON::valuedouble.
Referenced by cjson_get_number_value_should_get_a_number.
const char* cJSON_Version(void)
Referenced by main.
static int case_insensitive_strcmp(const unsigned char *string1, const unsigned char *string2)
Referenced by get_object_item.
static unsigned char* cJSON_strdup(const unsigned char *string, const internal_hooks *const hooks)
References internal_hooks::allocate.
Referenced by add_item_to_object, cjson_add_item_to_object_should_not_use_after_free_when_string_is_aliased, cJSON_CreateRaw, cJSON_CreateString, cJSON_Duplicate, cJSON_SetValuestring, replace_item_in_object.
void cJSON_InitHooks(cJSON_Hooks *hooks)
References internal_hooks::allocate, internal_hooks::deallocate, cJSON_Hooks::free_fn, global_hooks, cJSON_Hooks::malloc_fn, internal_hooks::reallocate.
Referenced by cjson_add_array_should_fail_on_allocation_failure, cjson_add_bool_should_fail_on_allocation_failure, cjson_add_false_should_fail_on_allocation_failure, cjson_add_null_should_fail_on_allocation_failure, cjson_add_number_should_fail_on_allocation_failure, cjson_add_object_should_fail_on_allocation_failure, cjson_add_raw_should_fail_on_allocation_failure, cjson_add_string_should_fail_on_allocation_failure, cjson_add_true_should_fail_on_allocation_failure, cjson_create_double_array_should_fail_on_allocation_failure, cjson_create_float_array_should_fail_on_allocation_failure, cjson_create_int_array_should_fail_on_allocation_failure, cjson_create_string_array_should_fail_on_allocation_failure, cjson_functions_should_not_crash_with_null_pointers.
static cJSON* cJSON_New_Item(const internal_hooks *const hooks)
References internal_hooks::allocate.
Referenced by cJSON_CreateArray, cJSON_CreateArrayReference, cJSON_CreateBool, cJSON_CreateFalse, cJSON_CreateNull, cJSON_CreateNumber, cJSON_CreateObject, cJSON_CreateObjectReference, cJSON_CreateRaw, cJSON_CreateString, cJSON_CreateStringReference, cJSON_CreateTrue, cJSON_Duplicate, cJSON_ParseWithLengthOpts, create_reference, parse_array, parse_object.
void cJSON_Delete(cJSON *item)
References cJSON::child, cJSON_Delete, internal_hooks::deallocate, global_hooks, cJSON::next, cJSON::string, cJSON::type, cJSON::valuestring.
Referenced by apply_patch, cJSON_add_array_should_add_array, cjson_add_array_should_fail_on_allocation_failure, cjson_add_array_should_fail_with_null_pointers, cjson_add_bool_should_add_bool, cjson_add_bool_should_fail_on_allocation_failure, cjson_add_bool_should_fail_with_null_pointers, cjson_add_false_should_add_false, cjson_add_false_should_fail_on_allocation_failure, cjson_add_false_should_fail_with_null_pointers, cjson_add_item_to_object_or_array_should_not_add_itself, cjson_add_item_to_object_should_not_use_after_free_when_string_is_aliased, cjson_add_null_should_add_null, cjson_add_null_should_fail_on_allocation_failure, cjson_add_null_should_fail_with_null_pointers, cjson_add_number_should_add_number, cjson_add_number_should_fail_on_allocation_failure, cjson_add_number_should_fail_with_null_pointers, cJSON_add_object_should_add_object, cjson_add_object_should_fail_on_allocation_failure, cjson_add_object_should_fail_with_null_pointers, cjson_add_raw_should_add_raw, cjson_add_raw_should_fail_on_allocation_failure, cjson_add_raw_should_fail_with_null_pointers, cjson_add_string_should_add_string, cjson_add_string_should_fail_on_allocation_failure, cjson_add_string_should_fail_with_null_pointers, cjson_add_true_should_add_true, cjson_add_true_should_fail_on_allocation_failure, cjson_add_true_should_fail_with_null_pointers, cJSON_AddArrayToObject, cJSON_AddBoolToObject, cJSON_AddFalseToObject, cJSON_AddNullToObject, cJSON_AddNumberToObject, cJSON_AddObjectToObject, cJSON_AddRawToObject, cJSON_AddStringToObject, cJSON_AddTrueToObject, cjson_compare_should_compare_raw, cjson_create_array_reference_should_create_an_array_reference, cjson_create_object_reference_should_create_an_object_reference, cjson_create_string_reference_should_create_a_string_reference, cJSON_CreateDoubleArray, cJSON_CreateFloatArray, cJSON_CreateIntArray, cJSON_CreateRaw, cJSON_CreateString, cJSON_CreateStringArray, cJSON_Delete, cjson_delete_item_from_array_should_not_broken_list_structure, cJSON_DeleteItemFromArray, cJSON_DeleteItemFromObject, cJSON_DeleteItemFromObjectCaseSensitive, cJSON_Duplicate, cjson_functions_should_not_crash_with_null_pointers, cjson_get_number_value_should_get_a_number, cjson_get_object_item_case_sensitive_should_get_object_items, cjson_get_object_item_case_sensitive_should_not_crash_with_array, cjson_get_object_item_should_get_object_items, cjson_get_object_item_should_not_crash_with_array, cjson_get_string_value_should_get_a_string, cJSON_ParseWithLengthOpts, cjson_replace_item_in_object_should_preserve_name, cJSON_ReplaceItemViaPointer, cjson_set_valuestring_to_object_should_not_leak_memory, cjson_utils_functions_shouldnt_crash_with_null_pointers, cjson_utils_should_pass_json_patch_test_cjson_utils_tests, cjson_utils_should_pass_json_patch_test_spec_tests, cjson_utils_should_pass_json_patch_test_tests, compare_from_string, create_monitor, create_monitor_with_helpers, create_objects, do_test, file_test6_should_not_be_parsed, generate_merge_patch, generate_merge_tests, json_pointer_tests, LLVMFuzzerTestOneInput, main, merge_patch, merge_tests, misc_tests, overwrite_item, parse_array, parse_object, parse_with_opts_should_handle_null, parse_with_opts_should_parse_utf8_bom, parse_with_opts_should_require_null_if_requested, parse_with_opts_should_return_parse_end, reset, sort_tests, supports_full_hd, test12_should_not_be_parsed, test13_should_be_parsed_without_null_termination, test14_should_not_be_parsed, test_apply_patch, test_generate_test.
static unsigned char get_decimal_point(void)
Referenced by parse_number, print_number.
static cJSON_bool parse_number(cJSON *const item, parse_buffer *const input_buffer)
References parse_buffer::content, get_decimal_point, parse_buffer::offset, cJSON::type, cJSON::valuedouble, cJSON::valueint.
Referenced by assert_parse_number, parse_value.
double cJSON_SetNumberHelper(cJSON *object, double number)
References cJSON::valuedouble, cJSON::valueint.
char* cJSON_SetValuestring(cJSON *object, const char *valuestring)
References cJSON_free, cJSON_strdup, global_hooks, cJSON::type, cJSON::valuestring.
Referenced by cjson_set_valuestring_to_object_should_not_leak_memory.
static unsigned char* ensure(printbuffer *const p, size_t needed)
References internal_hooks::allocate, printbuffer::buffer, internal_hooks::deallocate, printbuffer::hooks, printbuffer::length, printbuffer::noalloc, printbuffer::offset, internal_hooks::reallocate.
Referenced by ensure_should_fail_on_failed_realloc, print_array, print_number, print_object, print_string_ptr, print_value.
static void update_offset(printbuffer *const buffer)
References printbuffer::buffer, printbuffer::offset.
Referenced by print, print_array, print_object.
static cJSON_bool compare_double(double a, double b)
Referenced by cJSON_Compare, print_number, supports_full_hd.
static cJSON_bool print_number(const cJSON *const item, printbuffer *const output_buffer)
References compare_double, ensure, get_decimal_point, printbuffer::offset, cJSON::valuedouble.
Referenced by assert_print_number, print_value.
static unsigned parse_hex4(const unsigned char *const input)
Referenced by parse_hex4_should_parse_all_combinations, parse_hex4_should_parse_mixed_case, utf16_literal_to_utf8.
static unsigned char utf16_literal_to_utf8(const unsigned char *const input_pointer, const unsigned char *const input_end, unsigned char **output_pointer)
References parse_hex4.
Referenced by parse_string.
static cJSON_bool parse_string(cJSON *const item, parse_buffer *const input_buffer)
References internal_hooks::allocate, parse_buffer::content, internal_hooks::deallocate, parse_buffer::hooks, parse_buffer::length, parse_buffer::offset, cJSON::type, utf16_literal_to_utf8, cJSON::valuestring.
Referenced by assert_not_parse_string, assert_parse_string, parse_object, parse_value.
static cJSON_bool print_string_ptr(const unsigned char *const input, printbuffer *const output_buffer)
References ensure.
Referenced by assert_print_string, print_object, print_string.
static cJSON_bool print_string(const cJSON *const item, printbuffer *const p)
References print_string_ptr, cJSON::valuestring.
Referenced by print_value.
static cJSON_bool parse_value(cJSON *const item, parse_buffer *const input_buffer)
References parse_buffer::content, parse_buffer::offset, parse_array, parse_number, parse_object, parse_string, cJSON::type, cJSON::valueint.
Referenced by assert_parse_value, assert_print_value, cJSON_ParseWithLengthOpts, parse_array, parse_object.
static cJSON_bool print_value(const cJSON *const item, printbuffer *const output_buffer)
References ensure, print_array, print_number, print_object, print_string, cJSON::type, cJSON::valuestring.
Referenced by assert_print_value, cJSON_PrintBuffered, cJSON_PrintPreallocated, print, print_array, print_object.
static cJSON_bool parse_array(cJSON *const item, parse_buffer *const input_buffer)
References buffer_skip_whitespace, cJSON::child, cJSON_Delete, cJSON_New_Item, parse_buffer::depth, parse_buffer::hooks, cJSON::next, parse_buffer::offset, parse_value, cJSON::prev, cJSON::type.
Referenced by assert_not_array, assert_parse_array, assert_print_array, parse_value.
static cJSON_bool print_array(const cJSON *const item, printbuffer *const output_buffer)
References cJSON::child, printbuffer::depth, ensure, printbuffer::format, cJSON::next, printbuffer::offset, print_value, update_offset.
Referenced by assert_print_array, print_value.
static cJSON_bool parse_object(cJSON *const item, parse_buffer *const input_buffer)
References buffer_skip_whitespace, cJSON::child, cJSON_Delete, cJSON_New_Item, parse_buffer::depth, parse_buffer::hooks, cJSON::next, parse_buffer::offset, parse_string, parse_value, cJSON::prev, cJSON::string, cJSON::type, cJSON::valuestring.
Referenced by assert_not_object, assert_parse_object, assert_print_object, parse_value.
static cJSON_bool print_object(const cJSON *const item, printbuffer *const output_buffer)
References cJSON::child, printbuffer::depth, ensure, printbuffer::format, cJSON::next, printbuffer::offset, print_string_ptr, print_value, cJSON::string, update_offset.
Referenced by assert_print_object, print_value.
static parse_buffer* buffer_skip_whitespace(parse_buffer *const buffer)
References parse_buffer::content, parse_buffer::length, parse_buffer::offset.
Referenced by cJSON_ParseWithLengthOpts, parse_array, parse_object.
static parse_buffer* skip_utf8_bom(parse_buffer *const buffer)
References parse_buffer::content, parse_buffer::offset.
Referenced by cJSON_ParseWithLengthOpts, skip_utf8_bom_should_not_skip_bom_if_not_at_beginning, skip_utf8_bom_should_skip_bom.
cJSON* cJSON_ParseWithOpts(const char *value, const char **return_parse_end, cJSON_bool require_null_terminated)
References cJSON_ParseWithLengthOpts.
Referenced by cjson_functions_should_not_crash_with_null_pointers, cJSON_Parse, LLVMFuzzerTestOneInput, parse_with_opts_should_handle_empty_strings, parse_with_opts_should_handle_incomplete_json, parse_with_opts_should_handle_null, parse_with_opts_should_parse_utf8_bom, parse_with_opts_should_require_null_if_requested, parse_with_opts_should_return_parse_end.
cJSON* cJSON_ParseWithLengthOpts(const char *value, size_t buffer_length, const char **return_parse_end, cJSON_bool require_null_terminated)
References buffer_skip_whitespace, cJSON_Delete, cJSON_New_Item, parse_buffer::content, global_error, global_hooks, parse_buffer::hooks, error::json, parse_buffer::length, parse_buffer::offset, parse_value, error::position, skip_utf8_bom.
Referenced by cJSON_ParseWithLength, cJSON_ParseWithOpts.
cJSON* cJSON_Parse(const char *value)
References cJSON_ParseWithOpts.
Referenced by cjson_compare_should_compare_raw, cjson_delete_item_from_array_should_not_broken_list_structure, cjson_functions_should_not_crash_with_null_pointers, cjson_get_object_item_case_sensitive_should_get_object_items, cjson_get_object_item_case_sensitive_should_not_crash_with_array, cjson_get_object_item_should_get_object_items, cjson_get_object_item_should_not_crash_with_array, cjson_set_valuestring_to_object_should_not_leak_memory, cjson_should_not_parse_to_deeply_nested_jsons, compare_from_string, file_test6_should_not_be_parsed, generate_merge_tests, json_pointer_tests, main, merge_tests, parse_file, parse_test_file, supports_full_hd, test12_should_not_be_parsed.
cJSON* cJSON_ParseWithLength(const char *value, size_t buffer_length)
References cJSON_ParseWithLengthOpts.
Referenced by test13_should_be_parsed_without_null_termination, test14_should_not_be_parsed.
static unsigned char* print(const cJSON *const item, cJSON_bool format, const internal_hooks *const hooks)
References internal_hooks::allocate, printbuffer::buffer, internal_hooks::deallocate, printbuffer::format, printbuffer::hooks, printbuffer::length, printbuffer::offset, print_value, internal_hooks::reallocate, update_offset.
Referenced by cJSON_Print, cJSON_PrintUnformatted.
char* cJSON_Print(const cJSON *item)
References global_hooks, print.
Referenced by cjson_functions_should_not_crash_with_null_pointers, create_monitor, create_monitor_with_helpers, do_test, LLVMFuzzerTestOneInput, main, print_preallocated, test_generate_test.
char* cJSON_PrintUnformatted(const cJSON *item)
References global_hooks, print.
Referenced by cjson_delete_item_from_array_should_not_broken_list_structure, cjson_functions_should_not_crash_with_null_pointers, generate_merge_tests, LLVMFuzzerTestOneInput, main, merge_tests.
char* cJSON_PrintBuffered(const cJSON *item, int prebuffer, cJSON_bool fmt)
References internal_hooks::allocate, printbuffer::buffer, internal_hooks::deallocate, printbuffer::format, global_hooks, printbuffer::hooks, printbuffer::length, printbuffer::noalloc, printbuffer::offset, print_value.
Referenced by cjson_functions_should_not_crash_with_null_pointers, LLVMFuzzerTestOneInput, main.
cJSON_bool cJSON_PrintPreallocated(cJSON *item, char *buffer, const int length, const cJSON_bool format)
References printbuffer::buffer, printbuffer::format, global_hooks, printbuffer::hooks, printbuffer::length, printbuffer::noalloc, printbuffer::offset, print_value.
Referenced by cjson_functions_should_not_crash_with_null_pointers, print_preallocated.
int cJSON_GetArraySize(const cJSON *array)
References cJSON::child, cJSON::next.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
static cJSON* get_array_item(const cJSON *array, size_t index)
References cJSON::child, cJSON::next.
Referenced by cJSON_DetachItemFromArray, cJSON_GetArrayItem, cJSON_InsertItemInArray, cJSON_ReplaceItemInArray.
cJSON* cJSON_GetArrayItem(const cJSON *array, int index)
References get_array_item.
Referenced by cjson_functions_should_not_crash_with_null_pointers, misc_tests.
static cJSON* get_object_item(const cJSON *const object, const char *const name, const cJSON_bool case_sensitive)
References case_insensitive_strcmp, cJSON::child, cJSON::next, cJSON::string.
Referenced by cJSON_Compare, cJSON_GetObjectItem, cJSON_GetObjectItemCaseSensitive, replace_item_in_object.
cJSON* cJSON_GetObjectItem(const cJSON *const object, const char *const string)
References get_object_item.
Referenced by cJSON_DetachItemFromObject, cjson_functions_should_not_crash_with_null_pointers, cjson_get_object_item_should_get_object_items, cjson_get_object_item_should_not_crash_with_array, cJSON_HasObjectItem, cjson_set_valuestring_to_object_should_not_leak_memory, decode_patch_operation, json_pointer_tests.
cJSON* cJSON_GetObjectItemCaseSensitive(const cJSON *const object, const char *const string)
References get_object_item.
Referenced by cJSON_add_array_should_add_array, cjson_add_bool_should_add_bool, cjson_add_false_should_add_false, cjson_add_null_should_add_null, cjson_add_number_should_add_number, cJSON_add_object_should_add_object, cjson_add_raw_should_add_raw, cjson_add_string_should_add_string, cjson_add_true_should_add_true, cJSON_DetachItemFromObjectCaseSensitive, cjson_functions_should_not_crash_with_null_pointers, cjson_get_object_item_case_sensitive_should_get_object_items, cjson_get_object_item_case_sensitive_should_not_crash_with_array, decode_patch_operation, supports_full_hd, test_apply_patch, test_generate_test.
cJSON_bool cJSON_HasObjectItem(const cJSON *object, const char *string)
References cJSON_GetObjectItem.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
static void suffix_object(cJSON *prev, cJSON *item)
References cJSON::next, cJSON::prev.
Referenced by add_item_to_array, cJSON_CreateDoubleArray, cJSON_CreateFloatArray, cJSON_CreateIntArray, cJSON_CreateStringArray.
static cJSON* create_reference(const cJSON *item, const internal_hooks *const hooks)
References cJSON_New_Item, cJSON::next, cJSON::prev, cJSON::string, cJSON::type.
Referenced by cJSON_AddItemReferenceToArray, cJSON_AddItemReferenceToObject.
static cJSON_bool add_item_to_array(cJSON *array, cJSON *item)
References cJSON::child, cJSON::next, cJSON::prev, suffix_object.
Referenced by add_item_to_object, cJSON_AddItemReferenceToArray, cJSON_AddItemToArray, cJSON_InsertItemInArray.
cJSON_bool cJSON_AddItemToArray(cJSON *array, cJSON *item)
References add_item_to_array.
Referenced by apply_patch, cjson_add_item_to_object_or_array_should_not_add_itself, cjson_create_array_reference_should_create_an_array_reference, cjson_delete_item_from_array_should_not_broken_list_structure, cjson_functions_should_not_crash_with_null_pointers, cjson_replace_item_via_pointer_should_replace_items, compose_patch, create_monitor, create_monitor_with_helpers, create_objects, insert_item_in_array.
static void* cast_away_const(const void *string)
Referenced by add_item_to_object, cJSON_CreateArrayReference, cJSON_CreateObjectReference, cJSON_CreateStringReference.
static cJSON_bool add_item_to_object(cJSON *const object, const char *const string, cJSON *const item, const internal_hooks *const hooks, const cJSON_bool constant_key)
References add_item_to_array, cast_away_const, cJSON_strdup, internal_hooks::deallocate, cJSON::string, cJSON::type.
Referenced by cJSON_AddArrayToObject, cJSON_AddBoolToObject, cJSON_AddFalseToObject, cJSON_AddItemReferenceToObject, cJSON_AddItemToObject, cJSON_AddItemToObjectCS, cJSON_AddNullToObject, cJSON_AddNumberToObject, cJSON_AddObjectToObject, cJSON_AddRawToObject, cJSON_AddStringToObject, cJSON_AddTrueToObject.
cJSON_bool cJSON_AddItemToObject(cJSON *object, const char *string, cJSON *item)
References add_item_to_object, global_hooks.
Referenced by apply_patch, cjson_add_item_to_object_or_array_should_not_add_itself, cjson_add_item_to_object_should_not_use_after_free_when_string_is_aliased, cjson_functions_should_not_crash_with_null_pointers, cjson_replace_item_in_object_should_preserve_name, cjson_set_valuestring_to_object_should_not_leak_memory, compose_patch, create_monitor, create_objects, generate_merge_patch, merge_patch, misc_tests, sort_tests.
cJSON_bool cJSON_AddItemToObjectCS(cJSON *object, const char *string, cJSON *item)
References add_item_to_object, global_hooks.
Referenced by cjson_create_object_reference_should_create_an_object_reference, cjson_functions_should_not_crash_with_null_pointers.
cJSON_bool cJSON_AddItemReferenceToArray(cJSON *array, cJSON *item)
References add_item_to_array, create_reference, global_hooks.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
cJSON_bool cJSON_AddItemReferenceToObject(cJSON *object, const char *string, cJSON *item)
References add_item_to_object, create_reference, global_hooks.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_AddNullToObject(cJSON *const object, const char *const name)
References add_item_to_object, cJSON_CreateNull, cJSON_Delete, global_hooks.
Referenced by cjson_add_null_should_add_null, cjson_add_null_should_fail_on_allocation_failure, cjson_add_null_should_fail_with_null_pointers.
cJSON* cJSON_AddTrueToObject(cJSON *const object, const char *const name)
References add_item_to_object, cJSON_CreateTrue, cJSON_Delete, global_hooks.
Referenced by cjson_add_true_should_add_true, cjson_add_true_should_fail_on_allocation_failure, cjson_add_true_should_fail_with_null_pointers.
cJSON* cJSON_AddFalseToObject(cJSON *const object, const char *const name)
References add_item_to_object, cJSON_CreateFalse, cJSON_Delete, global_hooks.
Referenced by cjson_add_false_should_add_false, cjson_add_false_should_fail_on_allocation_failure, cjson_add_false_should_fail_with_null_pointers, create_objects.
cJSON* cJSON_AddBoolToObject(cJSON *const object, const char *const name, const cJSON_bool boolean)
References add_item_to_object, cJSON_CreateBool, cJSON_Delete, global_hooks.
Referenced by cjson_add_bool_should_add_bool, cjson_add_bool_should_fail_on_allocation_failure, cjson_add_bool_should_fail_with_null_pointers.
cJSON* cJSON_AddNumberToObject(cJSON *const object, const char *const name, const double number)
References add_item_to_object, cJSON_CreateNumber, cJSON_Delete, global_hooks.
Referenced by cjson_add_number_should_add_number, cjson_add_number_should_fail_on_allocation_failure, cjson_add_number_should_fail_with_null_pointers, create_monitor_with_helpers, create_objects.
cJSON* cJSON_AddStringToObject(cJSON *const object, const char *const name, const char *const string)
References add_item_to_object, cJSON_CreateString, cJSON_Delete, global_hooks.
Referenced by cjson_add_string_should_add_string, cjson_add_string_should_fail_on_allocation_failure, cjson_add_string_should_fail_with_null_pointers, create_monitor_with_helpers, create_objects.
cJSON* cJSON_AddRawToObject(cJSON *const object, const char *const name, const char *const raw)
References add_item_to_object, cJSON_CreateRaw, cJSON_Delete, global_hooks.
Referenced by cjson_add_raw_should_add_raw, cjson_add_raw_should_fail_on_allocation_failure, cjson_add_raw_should_fail_with_null_pointers.
cJSON* cJSON_AddObjectToObject(cJSON *const object, const char *const name)
References add_item_to_object, cJSON_CreateObject, cJSON_Delete, global_hooks.
Referenced by cJSON_add_object_should_add_object, cjson_add_object_should_fail_on_allocation_failure, cjson_add_object_should_fail_with_null_pointers.
cJSON* cJSON_AddArrayToObject(cJSON *const object, const char *const name)
References add_item_to_object, cJSON_CreateArray, cJSON_Delete, global_hooks.
Referenced by cJSON_add_array_should_add_array, cjson_add_array_should_fail_on_allocation_failure, cjson_add_array_should_fail_with_null_pointers, cjson_delete_item_from_array_should_not_broken_list_structure, create_monitor_with_helpers.
cJSON* cJSON_DetachItemViaPointer(cJSON *parent, cJSON *const item)
References cJSON::child, cJSON::next, cJSON::prev.
Referenced by cjson_detach_item_via_pointer_should_detach_items, cJSON_DetachItemFromArray, cJSON_DetachItemFromObject, cJSON_DetachItemFromObjectCaseSensitive, cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_DetachItemFromArray(cJSON *array, int which)
References cJSON_DetachItemViaPointer, get_array_item.
Referenced by cJSON_DeleteItemFromArray, cjson_functions_should_not_crash_with_null_pointers.
void cJSON_DeleteItemFromArray(cJSON *array, int which)
References cJSON_Delete, cJSON_DetachItemFromArray.
Referenced by cjson_delete_item_from_array_should_not_broken_list_structure, cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_DetachItemFromObject(cJSON *object, const char *string)
References cJSON_DetachItemViaPointer, cJSON_GetObjectItem.
Referenced by cJSON_DeleteItemFromObject, cjson_functions_should_not_crash_with_null_pointers, detach_path, merge_patch.
cJSON* cJSON_DetachItemFromObjectCaseSensitive(cJSON *object, const char *string)
References cJSON_DetachItemViaPointer, cJSON_GetObjectItemCaseSensitive.
Referenced by cJSON_DeleteItemFromObjectCaseSensitive, cjson_functions_should_not_crash_with_null_pointers, merge_patch.
void cJSON_DeleteItemFromObject(cJSON *object, const char *string)
References cJSON_Delete, cJSON_DetachItemFromObject.
Referenced by apply_patch, cjson_functions_should_not_crash_with_null_pointers, merge_patch.
void cJSON_DeleteItemFromObjectCaseSensitive(cJSON *object, const char *string)
References cJSON_Delete, cJSON_DetachItemFromObjectCaseSensitive.
Referenced by apply_patch, cjson_functions_should_not_crash_with_null_pointers, merge_patch.
cJSON_bool cJSON_InsertItemInArray(cJSON *array, int which, cJSON *newitem)
References add_item_to_array, cJSON::child, get_array_item, cJSON::next, cJSON::prev.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
cJSON_bool cJSON_ReplaceItemViaPointer(cJSON *const parent, cJSON *const item, cJSON *replacement)
References cJSON::child, cJSON_Delete, cJSON::next, cJSON::prev.
Referenced by cjson_functions_should_not_crash_with_null_pointers, cjson_replace_item_via_pointer_should_replace_items, cJSON_ReplaceItemInArray, replace_item_in_object.
cJSON_bool cJSON_ReplaceItemInArray(cJSON *array, int which, cJSON *newitem)
References cJSON_ReplaceItemViaPointer, get_array_item.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
static cJSON_bool replace_item_in_object(cJSON *object, const char *string, cJSON *replacement, cJSON_bool case_sensitive)
References cJSON_free, cJSON_ReplaceItemViaPointer, cJSON_strdup, get_object_item, global_hooks, cJSON::string, cJSON::type.
Referenced by cJSON_ReplaceItemInObject, cJSON_ReplaceItemInObjectCaseSensitive.
cJSON_bool cJSON_ReplaceItemInObject(cJSON *object, const char *string, cJSON *newitem)
References replace_item_in_object.
Referenced by cjson_functions_should_not_crash_with_null_pointers, cjson_replace_item_in_object_should_preserve_name.
cJSON_bool cJSON_ReplaceItemInObjectCaseSensitive(cJSON *object, const char *string, cJSON *newitem)
References replace_item_in_object.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_CreateNull(void)
References cJSON_New_Item, global_hooks, cJSON::type.
Referenced by cJSON_AddNullToObject, cjson_replace_item_via_pointer_should_replace_items, generate_merge_patch.
cJSON* cJSON_CreateTrue(void)
References cJSON_New_Item, global_hooks, cJSON::type.
Referenced by cJSON_AddTrueToObject.
cJSON* cJSON_CreateFalse(void)
References cJSON_New_Item, global_hooks, cJSON::type.
Referenced by cJSON_AddFalseToObject.
cJSON* cJSON_CreateBool(cJSON_bool boolean)
References cJSON_New_Item, global_hooks, cJSON::type.
Referenced by cJSON_AddBoolToObject.
cJSON* cJSON_CreateNumber(double num)
References cJSON_New_Item, global_hooks, cJSON::type, cJSON::valuedouble, cJSON::valueint.
Referenced by cjson_add_item_to_object_should_not_use_after_free_when_string_is_aliased, cJSON_AddNumberToObject, cjson_create_array_reference_should_create_an_array_reference, cjson_create_object_reference_should_create_an_object_reference, cJSON_CreateDoubleArray, cJSON_CreateFloatArray, cJSON_CreateIntArray, cjson_get_number_value_should_get_a_number, cjson_get_string_value_should_get_a_string, cjson_replace_item_in_object_should_preserve_name, create_monitor, sort_tests.
cJSON* cJSON_CreateString(const char *string)
References cJSON_Delete, cJSON_New_Item, cJSON_strdup, global_hooks, cJSON::type, cJSON::valuestring.
Referenced by cJSON_AddStringToObject, cJSON_CreateStringArray, cjson_functions_should_not_crash_with_null_pointers, cjson_get_number_value_should_get_a_number, cjson_get_string_value_should_get_a_string, cjson_set_valuestring_to_object_should_not_leak_memory, cjson_utils_functions_shouldnt_crash_with_null_pointers, compose_patch, create_monitor, create_objects, misc_tests.
cJSON* cJSON_CreateStringReference(const char *string)
References cast_away_const, cJSON_New_Item, global_hooks, cJSON::type, cJSON::valuestring.
Referenced by cjson_create_string_reference_should_create_a_string_reference, cjson_set_valuestring_to_object_should_not_leak_memory.
cJSON* cJSON_CreateObjectReference(const cJSON *child)
References cast_away_const, cJSON::child, cJSON_New_Item, global_hooks, cJSON::type.
Referenced by cjson_create_object_reference_should_create_an_object_reference.
cJSON* cJSON_CreateArrayReference(const cJSON *child)
References cast_away_const, cJSON::child, cJSON_New_Item, global_hooks, cJSON::type.
Referenced by cjson_create_array_reference_should_create_an_array_reference.
cJSON* cJSON_CreateRaw(const char *raw)
References cJSON_Delete, cJSON_New_Item, cJSON_strdup, global_hooks, cJSON::type, cJSON::valuestring.
Referenced by cJSON_AddRawToObject, cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_CreateArray(void)
References cJSON_New_Item, global_hooks, cJSON::type.
Referenced by cjson_add_item_to_object_or_array_should_not_add_itself, cJSON_AddArrayToObject, cjson_create_array_reference_should_create_an_array_reference, cJSON_CreateDoubleArray, cJSON_CreateFloatArray, cJSON_CreateIntArray, cJSON_CreateStringArray, cjson_replace_item_via_pointer_should_replace_items, cJSONUtils_GeneratePatches, cJSONUtils_GeneratePatchesCaseSensitive, create_monitor, create_objects.
cJSON* cJSON_CreateObject(void)
References cJSON_New_Item, global_hooks, cJSON::type.
Referenced by cJSON_add_array_should_add_array, cjson_add_array_should_fail_on_allocation_failure, cjson_add_array_should_fail_with_null_pointers, cjson_add_bool_should_add_bool, cjson_add_bool_should_fail_on_allocation_failure, cjson_add_bool_should_fail_with_null_pointers, cjson_add_false_should_add_false, cjson_add_false_should_fail_on_allocation_failure, cjson_add_false_should_fail_with_null_pointers, cjson_add_item_to_object_or_array_should_not_add_itself, cjson_add_item_to_object_should_not_use_after_free_when_string_is_aliased, cjson_add_null_should_add_null, cjson_add_null_should_fail_on_allocation_failure, cjson_add_null_should_fail_with_null_pointers, cjson_add_number_should_add_number, cjson_add_number_should_fail_on_allocation_failure, cjson_add_number_should_fail_with_null_pointers, cJSON_add_object_should_add_object, cjson_add_object_should_fail_on_allocation_failure, cjson_add_object_should_fail_with_null_pointers, cjson_add_raw_should_add_raw, cjson_add_raw_should_fail_on_allocation_failure, cjson_add_raw_should_fail_with_null_pointers, cjson_add_string_should_add_string, cjson_add_string_should_fail_on_allocation_failure, cjson_add_string_should_fail_with_null_pointers, cjson_add_true_should_add_true, cjson_add_true_should_fail_on_allocation_failure, cjson_add_true_should_fail_with_null_pointers, cJSON_AddObjectToObject, cjson_create_object_reference_should_create_an_object_reference, compose_patch, create_monitor, create_monitor_with_helpers, create_objects, generate_merge_patch, merge_patch, misc_tests, sort_tests.
cJSON* cJSON_CreateIntArray(const int *numbers, int count)
References cJSON::child, cJSON_CreateArray, cJSON_CreateNumber, cJSON_Delete, cJSON::prev, suffix_object.
Referenced by cjson_create_int_array_should_fail_on_allocation_failure, cjson_functions_should_not_crash_with_null_pointers, create_objects, misc_tests.
cJSON* cJSON_CreateFloatArray(const float *numbers, int count)
References cJSON::child, cJSON_CreateArray, cJSON_CreateNumber, cJSON_Delete, cJSON::prev, suffix_object.
Referenced by cjson_create_float_array_should_fail_on_allocation_failure, cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_CreateDoubleArray(const double *numbers, int count)
References cJSON::child, cJSON_CreateArray, cJSON_CreateNumber, cJSON_Delete, cJSON::prev, suffix_object.
Referenced by cjson_create_double_array_should_fail_on_allocation_failure, cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_CreateStringArray(const char *const *strings, int count)
References cJSON::child, cJSON_CreateArray, cJSON_CreateString, cJSON_Delete, cJSON::prev, suffix_object.
Referenced by cjson_create_string_array_should_fail_on_allocation_failure, cjson_functions_should_not_crash_with_null_pointers, create_objects.
cJSON* cJSON_Duplicate(const cJSON *item, cJSON_bool recurse)
References cJSON::child, cJSON_Delete, cJSON_Duplicate, cJSON_New_Item, cJSON_strdup, global_hooks, cJSON::next, cJSON::prev, cJSON::string, cJSON::type, cJSON::valuedouble, cJSON::valueint, cJSON::valuestring.
Referenced by apply_patch, cJSON_Duplicate, cjson_functions_should_not_crash_with_null_pointers, compose_patch, generate_merge_patch, merge_patch, test_apply_patch, test_generate_test.
static void skip_oneline_comment(char **input)
Referenced by cJSON_Minify.
static void skip_multiline_comment(char **input)
Referenced by cJSON_Minify.
static void minify_string(char **input, char **output)
Referenced by cJSON_Minify.
void cJSON_Minify(char *json)
References minify_string, skip_multiline_comment, skip_oneline_comment.
Referenced by cjson_functions_should_not_crash_with_null_pointers, cjson_minify_should_minify_json, cjson_minify_should_not_loop_infinitely, cjson_minify_should_not_modify_strings, cjson_minify_should_not_overflow_buffer, cjson_minify_should_remove_multiline_comments, cjson_minify_should_remove_single_line_comments, cjson_minify_should_remove_spaces, LLVMFuzzerTestOneInput.
cJSON_bool cJSON_IsInvalid(const cJSON *const item)
References cJSON::type.
Referenced by cJSON_Compare, cjson_functions_should_not_crash_with_null_pointers, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsFalse(const cJSON *const item)
References cJSON::type.
Referenced by cjson_functions_should_not_crash_with_null_pointers, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsTrue(const cJSON *const item)
References cJSON::type.
Referenced by cjson_functions_should_not_crash_with_null_pointers, test_apply_patch, test_generate_test, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsBool(const cJSON *const item)
References cJSON::type.
Referenced by cjson_functions_should_not_crash_with_null_pointers, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsNull(const cJSON *const item)
References cJSON::type.
Referenced by cjson_functions_should_not_crash_with_null_pointers, merge_patch, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsNumber(const cJSON *const item)
References cJSON::type.
Referenced by cjson_create_array_reference_should_create_an_array_reference, cjson_create_object_reference_should_create_an_object_reference, cjson_functions_should_not_crash_with_null_pointers, cJSON_GetNumberValue, supports_full_hd, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsString(const cJSON *const item)
References cJSON::type.
Referenced by apply_patch, cjson_functions_should_not_crash_with_null_pointers, cJSON_GetStringValue, supports_full_hd, test_apply_patch, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsArray(const cJSON *const item)
References cJSON::type.
Referenced by apply_patch, cjson_create_array_reference_should_create_an_array_reference, cjson_functions_should_not_crash_with_null_pointers, cJSONUtils_ApplyPatches, cJSONUtils_ApplyPatchesCaseSensitive, cJSONUtils_FindPointerFromObjectTo, detach_path, get_item_from_pointer, parse_test_file, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsObject(const cJSON *const item)
References cJSON::type.
Referenced by apply_patch, cjson_create_object_reference_should_create_an_object_reference, cjson_functions_should_not_crash_with_null_pointers, cJSONUtils_FindPointerFromObjectTo, detach_path, generate_merge_patch, get_item_from_pointer, merge_patch, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsRaw(const cJSON *const item)
References cJSON::type.
Referenced by cjson_functions_should_not_crash_with_null_pointers, typecheck_functions_should_check_type.
cJSON_bool cJSON_Compare(const cJSON *const a, const cJSON *const b, const cJSON_bool case_sensitive)
References cJSON::child, cJSON_Compare, cJSON_IsInvalid, compare_double, get_object_item, cJSON::next, cJSON::string, cJSON::type, cJSON::valuedouble, cJSON::valuestring.
Referenced by cJSON_Compare, cjson_compare_should_compare_invalid_as_not_equal, cjson_compare_should_compare_null_pointer_as_not_equal, cjson_compare_should_compare_raw, cjson_compare_should_not_accept_invalid_types, cjson_functions_should_not_crash_with_null_pointers, compare_from_string, parse_with_opts_should_parse_utf8_bom, test_apply_patch, test_generate_test.
void* cJSON_malloc(size_t size)
References internal_hooks::allocate, global_hooks.
Referenced by cJSONUtils_FindPointerFromObjectTo, cJSONUtils_strdup, compose_patch, create_patches.
void cJSON_free(void *object)
References internal_hooks::deallocate, global_hooks.
Referenced by apply_patch, cjson_replace_item_via_pointer_should_replace_items, cJSON_SetValuestring, cJSONUtils_FindPointerFromObjectTo, compose_patch, create_patches, detach_path, overwrite_item, replace_item_in_object.