cJSON_Utils.c
true
false
patch_operation
static unsigned char* cJSONUtils_strdup(const unsigned char *const string)
References cJSON_malloc.
Referenced by apply_patch, cJSONUtils_FindPointerFromObjectTo, detach_path.
static int compare_strings(const unsigned char *string1, const unsigned char *string2, const cJSON_bool case_sensitive)
Referenced by compare_json, create_patches, sort_list.
static cJSON_bool compare_double(double a, double b)
Referenced by compare_json, create_patches.
static cJSON_bool compare_pointers(const unsigned char *name, const unsigned char *pointer, const cJSON_bool case_sensitive)
Referenced by get_item_from_pointer.
static size_t pointer_encoded_length(const unsigned char *string)
Referenced by cJSONUtils_FindPointerFromObjectTo, compose_patch, create_patches.
static void encode_string_as_pointer(unsigned char *destination, const unsigned char *source)
Referenced by cJSONUtils_FindPointerFromObjectTo, compose_patch, create_patches.
char* cJSONUtils_FindPointerFromObjectTo(const cJSON *const object, const cJSON *const target)
References cJSON::child, cJSON_free, cJSON_IsArray, cJSON_IsObject, cJSON_malloc, cJSONUtils_FindPointerFromObjectTo, cJSONUtils_strdup, encode_string_as_pointer, cJSON::next, pointer_encoded_length, cJSON::string.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers, cJSONUtils_FindPointerFromObjectTo, misc_tests.
static cJSON* get_array_item(const cJSON *array, size_t item)
References cJSON::child, cJSON::next.
Referenced by get_item_from_pointer.
static cJSON_bool decode_array_index_from_pointer(const unsigned char *const pointer, size_t *const index)
Referenced by apply_patch, detach_path, get_item_from_pointer.
static cJSON* get_item_from_pointer(cJSON *const object, const char *pointer, const cJSON_bool case_sensitive)
References cJSON::child, cJSON_IsArray, cJSON_IsObject, compare_pointers, decode_array_index_from_pointer, get_array_item, cJSON::next, cJSON::string.
Referenced by apply_patch, cJSONUtils_GetPointer, cJSONUtils_GetPointerCaseSensitive, detach_path.
cJSON* cJSONUtils_GetPointer(cJSON *const object, const char *pointer)
References get_item_from_pointer.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers, json_pointer_tests.
cJSON* cJSONUtils_GetPointerCaseSensitive(cJSON *const object, const char *pointer)
References get_item_from_pointer.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers.
static void decode_pointer_inplace(unsigned char *string)
Referenced by apply_patch, detach_path.
static cJSON* detach_item_from_array(cJSON *array, size_t which)
References cJSON::child, cJSON::next, cJSON::prev.
Referenced by detach_path.
static cJSON* detach_path(cJSON *object, const unsigned char *path, const cJSON_bool case_sensitive)
References cJSON_DetachItemFromObject, cJSON_free, cJSON_IsArray, cJSON_IsObject, cJSONUtils_strdup, decode_array_index_from_pointer, decode_pointer_inplace, detach_item_from_array, get_item_from_pointer.
Referenced by apply_patch.
static cJSON* sort_list(cJSON *list, const cJSON_bool case_sensitive)
References compare_strings, cJSON::next, cJSON::prev, sort_list, cJSON::string.
Referenced by sort_list, sort_object.
static void sort_object(cJSON *const object, const cJSON_bool case_sensitive)
References cJSON::child, sort_list.
Referenced by cJSONUtils_SortObject, cJSONUtils_SortObjectCaseSensitive, compare_json, create_patches, generate_merge_patch.
static cJSON_bool compare_json(cJSON *a, cJSON *b, const cJSON_bool case_sensitive)
References cJSON::child, compare_double, compare_json, compare_strings, cJSON::next, sort_object, cJSON::string, cJSON::type, cJSON::valuedouble, cJSON::valueint, cJSON::valuestring.
Referenced by apply_patch, compare_json, generate_merge_patch.
static cJSON_bool insert_item_in_array(cJSON *array, size_t which, cJSON *newitem)
References cJSON::child, cJSON_AddItemToArray, cJSON::next, cJSON::prev.
Referenced by apply_patch.
static cJSON* get_object_item(const cJSON *const object, const char *name, const cJSON_bool case_sensitive)
Referenced by apply_patch.
static enum patch_operation decode_patch_operation(const cJSON *const patch, const cJSON_bool case_sensitive)
References cJSON_GetObjectItem, cJSON_GetObjectItemCaseSensitive.
static void overwrite_item(cJSON *const root, const cJSON replacement)
References cJSON::child, cJSON_Delete, cJSON_free, cJSON::string, cJSON::valuestring.
Referenced by apply_patch.
static int apply_patch(cJSON *object, const cJSON *patch, const cJSON_bool case_sensitive)
References ADD, cJSON_AddItemToArray, cJSON_AddItemToObject, cJSON_Delete, cJSON_DeleteItemFromObject, cJSON_DeleteItemFromObjectCaseSensitive, cJSON_Duplicate, cJSON_free, cJSON_IsArray, cJSON_IsObject, cJSON_IsString, cJSONUtils_strdup, compare_json, COPY, decode_array_index_from_pointer, decode_pointer_inplace, detach_path, get_item_from_pointer, get_object_item, insert_item_in_array, INVALID, MOVE, overwrite_item, REMOVE, REPLACE, cJSON::string, TEST, cJSON::valuestring.
Referenced by cJSONUtils_ApplyPatches, cJSONUtils_ApplyPatchesCaseSensitive.
int cJSONUtils_ApplyPatches(cJSON *const object, const cJSON *const patches)
References apply_patch, cJSON::child, cJSON_IsArray, cJSON::next.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers.
int cJSONUtils_ApplyPatchesCaseSensitive(cJSON *const object, const cJSON *const patches)
References apply_patch, cJSON::child, cJSON_IsArray, cJSON::next.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers, test_apply_patch, test_generate_test.
static void compose_patch(cJSON *const patches, const unsigned char *const operation, const unsigned char *const path, const unsigned char *suffix, const cJSON *const value)
References cJSON_AddItemToArray, cJSON_AddItemToObject, cJSON_CreateObject, cJSON_CreateString, cJSON_Duplicate, cJSON_free, cJSON_malloc, encode_string_as_pointer, pointer_encoded_length.
Referenced by cJSONUtils_AddPatchToArray, create_patches.
void cJSONUtils_AddPatchToArray(cJSON *const array, const char *const operation, const char *const path, const cJSON *const value)
References compose_patch.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers.
static void create_patches(cJSON *const patches, const unsigned char *const path, cJSON *const from, cJSON *const to, const cJSON_bool case_sensitive)
References cJSON::child, cJSON_free, cJSON_malloc, compare_double, compare_strings, compose_patch, create_patches, encode_string_as_pointer, cJSON::next, pointer_encoded_length, sort_object, cJSON::string, cJSON::type, cJSON::valuedouble, cJSON::valueint, cJSON::valuestring.
Referenced by cJSONUtils_GeneratePatches, cJSONUtils_GeneratePatchesCaseSensitive, create_patches.
cJSON* cJSONUtils_GeneratePatches(cJSON *const from, cJSON *const to)
References cJSON_CreateArray, create_patches.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers.
cJSON* cJSONUtils_GeneratePatchesCaseSensitive(cJSON *const from, cJSON *const to)
References cJSON_CreateArray, create_patches.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers, test_generate_test.
void cJSONUtils_SortObject(cJSON *const object)
References sort_object.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers, sort_tests.
void cJSONUtils_SortObjectCaseSensitive(cJSON *const object)
References sort_object.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers.
static cJSON* merge_patch(cJSON *target, const cJSON *const patch, const cJSON_bool case_sensitive)
References cJSON::child, cJSON_AddItemToObject, cJSON_CreateObject, cJSON_Delete, cJSON_DeleteItemFromObject, cJSON_DeleteItemFromObjectCaseSensitive, cJSON_DetachItemFromObject, cJSON_DetachItemFromObjectCaseSensitive, cJSON_Duplicate, cJSON_IsNull, cJSON_IsObject, merge_patch, cJSON::next, cJSON::string.
Referenced by cJSONUtils_MergePatch, cJSONUtils_MergePatchCaseSensitive, merge_patch.
cJSON* cJSONUtils_MergePatch(cJSON *target, const cJSON *const patch)
References merge_patch.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers, generate_merge_tests, merge_tests.
cJSON* cJSONUtils_MergePatchCaseSensitive(cJSON *target, const cJSON *const patch)
References merge_patch.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers.
static cJSON* generate_merge_patch(cJSON *const from, cJSON *const to, const cJSON_bool case_sensitive)
References cJSON::child, cJSON_AddItemToObject, cJSON_CreateNull, cJSON_CreateObject, cJSON_Delete, cJSON_Duplicate, cJSON_IsObject, cJSONUtils_GenerateMergePatch, compare_json, cJSON::next, sort_object, cJSON::string.
Referenced by cJSONUtils_GenerateMergePatch, cJSONUtils_GenerateMergePatchCaseSensitive.
cJSON* cJSONUtils_GenerateMergePatch(cJSON *const from, cJSON *const to)
References generate_merge_patch.
Referenced by generate_merge_patch, generate_merge_tests.
cJSON* cJSONUtils_GenerateMergePatchCaseSensitive(cJSON *const from, cJSON *const to)
References generate_merge_patch.