cJSON.h
CJSON_CDECL
CJSON_STDCALL
CJSON_PUBLIC
CJSON_VERSION_MAJOR
CJSON_VERSION_MINOR
CJSON_VERSION_PATCH
cJSON_Invalid
cJSON_False
cJSON_True
cJSON_NULL
cJSON_Number
cJSON_String
cJSON_Array
cJSON_Object
cJSON_Raw
cJSON_IsReference
cJSON_StringIsConst
CJSON_NESTING_LIMIT
cJSON_SetIntValue
cJSON_SetNumberValue
cJSON_ArrayForEach
typedef struct cJSON cJSON
typedef struct cJSON_Hooks cJSON_Hooks
typedef int cJSON_bool
const char* cJSON_Version(void)
References CJSON_VERSION_MAJOR, CJSON_VERSION_MINOR, CJSON_VERSION_PATCH.
Referenced by main.
void cJSON_InitHooks(cJSON_Hooks *hooks)
References internal_hooks::allocate, internal_hooks::deallocate, free, cJSON_Hooks::free_fn, global_hooks, malloc, cJSON_Hooks::malloc_fn, realloc, internal_hooks::reallocate.
Referenced by cjson_add_array_should_fail_on_allocation_failure, cjson_add_bool_should_fail_on_allocation_failure, cjson_add_false_should_fail_on_allocation_failure, cjson_add_null_should_fail_on_allocation_failure, cjson_add_number_should_fail_on_allocation_failure, cjson_add_object_should_fail_on_allocation_failure, cjson_add_raw_should_fail_on_allocation_failure, cjson_add_string_should_fail_on_allocation_failure, cjson_add_true_should_fail_on_allocation_failure, cjson_create_double_array_should_fail_on_allocation_failure, cjson_create_float_array_should_fail_on_allocation_failure, cjson_create_int_array_should_fail_on_allocation_failure, cjson_create_string_array_should_fail_on_allocation_failure, cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_Parse(const char *value)
References cJSON_ParseWithOpts.
Referenced by cjson_compare_should_compare_raw, cjson_delete_item_from_array_should_not_broken_list_structure, cjson_functions_should_not_crash_with_null_pointers, cjson_get_object_item_case_sensitive_should_get_object_items, cjson_get_object_item_case_sensitive_should_not_crash_with_array, cjson_get_object_item_should_get_object_items, cjson_get_object_item_should_not_crash_with_array, cjson_set_valuestring_to_object_should_not_leak_memory, cjson_should_not_parse_to_deeply_nested_jsons, compare_from_string, file_test6_should_not_be_parsed, generate_merge_tests, json_pointer_tests, main, merge_tests, parse_file, parse_test_file, supports_full_hd, test12_should_not_be_parsed.
cJSON* cJSON_ParseWithLength(const char *value, size_t buffer_length)
References cJSON_ParseWithLengthOpts.
Referenced by test13_should_be_parsed_without_null_termination, test14_should_not_be_parsed.
cJSON* cJSON_ParseWithOpts(const char *value, const char **return_parse_end, cJSON_bool require_null_terminated)
References cJSON_ParseWithLengthOpts.
Referenced by cjson_functions_should_not_crash_with_null_pointers, cJSON_Parse, LLVMFuzzerTestOneInput, parse_with_opts_should_handle_empty_strings, parse_with_opts_should_handle_incomplete_json, parse_with_opts_should_handle_null, parse_with_opts_should_parse_utf8_bom, parse_with_opts_should_require_null_if_requested, parse_with_opts_should_return_parse_end.
cJSON* cJSON_ParseWithLengthOpts(const char *value, size_t buffer_length, const char **return_parse_end, cJSON_bool require_null_terminated)
References buffer, buffer_at_offset, buffer_skip_whitespace, cJSON_Delete, cJSON_New_Item, parse_buffer::content, global_error, global_hooks, parse_buffer::hooks, item, error::json, parse_buffer::length, parse_buffer::offset, parse_value, error::position, skip_utf8_bom.
Referenced by cJSON_ParseWithLength, cJSON_ParseWithOpts.
char* cJSON_Print(const cJSON *item)
References global_hooks, item, print.
Referenced by cjson_functions_should_not_crash_with_null_pointers, create_monitor, create_monitor_with_helpers, do_test, LLVMFuzzerTestOneInput, main, print_preallocated, test_generate_test.
char* cJSON_PrintUnformatted(const cJSON *item)
References global_hooks, item, print.
Referenced by cjson_delete_item_from_array_should_not_broken_list_structure, cjson_functions_should_not_crash_with_null_pointers, generate_merge_tests, LLVMFuzzerTestOneInput, main, merge_tests.
char* cJSON_PrintBuffered(const cJSON *item, int prebuffer, cJSON_bool fmt)
References internal_hooks::allocate, printbuffer::buffer, internal_hooks::deallocate, printbuffer::format, global_hooks, printbuffer::hooks, item, printbuffer::length, printbuffer::noalloc, printbuffer::offset, print_value.
Referenced by cjson_functions_should_not_crash_with_null_pointers, LLVMFuzzerTestOneInput, main.
cJSON_bool cJSON_PrintPreallocated(cJSON *item, char *buffer, const int length, const cJSON_bool format)
References printbuffer::buffer, buffer, printbuffer::format, global_hooks, printbuffer::hooks, item, printbuffer::length, printbuffer::noalloc, printbuffer::offset, print_value.
Referenced by cjson_functions_should_not_crash_with_null_pointers, print_preallocated.
void cJSON_Delete(cJSON *item)
References cJSON::child, cJSON_Delete, cJSON_IsReference, cJSON_StringIsConst, internal_hooks::deallocate, global_hooks, item, cJSON::next, cJSON::string, cJSON::type, cJSON::valuestring.
Referenced by apply_patch, cJSON_add_array_should_add_array, cjson_add_array_should_fail_on_allocation_failure, cjson_add_array_should_fail_with_null_pointers, cjson_add_bool_should_add_bool, cjson_add_bool_should_fail_on_allocation_failure, cjson_add_bool_should_fail_with_null_pointers, cjson_add_false_should_add_false, cjson_add_false_should_fail_on_allocation_failure, cjson_add_false_should_fail_with_null_pointers, cjson_add_item_to_object_or_array_should_not_add_itself, cjson_add_item_to_object_should_not_use_after_free_when_string_is_aliased, cjson_add_null_should_add_null, cjson_add_null_should_fail_on_allocation_failure, cjson_add_null_should_fail_with_null_pointers, cjson_add_number_should_add_number, cjson_add_number_should_fail_on_allocation_failure, cjson_add_number_should_fail_with_null_pointers, cJSON_add_object_should_add_object, cjson_add_object_should_fail_on_allocation_failure, cjson_add_object_should_fail_with_null_pointers, cjson_add_raw_should_add_raw, cjson_add_raw_should_fail_on_allocation_failure, cjson_add_raw_should_fail_with_null_pointers, cjson_add_string_should_add_string, cjson_add_string_should_fail_on_allocation_failure, cjson_add_string_should_fail_with_null_pointers, cjson_add_true_should_add_true, cjson_add_true_should_fail_on_allocation_failure, cjson_add_true_should_fail_with_null_pointers, cJSON_AddArrayToObject, cJSON_AddBoolToObject, cJSON_AddFalseToObject, cJSON_AddNullToObject, cJSON_AddNumberToObject, cJSON_AddObjectToObject, cJSON_AddRawToObject, cJSON_AddStringToObject, cJSON_AddTrueToObject, cjson_compare_should_compare_raw, cjson_create_array_reference_should_create_an_array_reference, cjson_create_object_reference_should_create_an_object_reference, cjson_create_string_reference_should_create_a_string_reference, cJSON_CreateDoubleArray, cJSON_CreateFloatArray, cJSON_CreateIntArray, cJSON_CreateRaw, cJSON_CreateString, cJSON_CreateStringArray, cJSON_Delete, cjson_delete_item_from_array_should_not_broken_list_structure, cJSON_DeleteItemFromArray, cJSON_DeleteItemFromObject, cJSON_DeleteItemFromObjectCaseSensitive, cJSON_Duplicate, cjson_functions_should_not_crash_with_null_pointers, cjson_get_number_value_should_get_a_number, cjson_get_object_item_case_sensitive_should_get_object_items, cjson_get_object_item_case_sensitive_should_not_crash_with_array, cjson_get_object_item_should_get_object_items, cjson_get_object_item_should_not_crash_with_array, cjson_get_string_value_should_get_a_string, cJSON_ParseWithLengthOpts, cjson_replace_item_in_object_should_preserve_name, cJSON_ReplaceItemViaPointer, cjson_set_valuestring_to_object_should_not_leak_memory, cjson_utils_functions_shouldnt_crash_with_null_pointers, cjson_utils_should_pass_json_patch_test_cjson_utils_tests, cjson_utils_should_pass_json_patch_test_spec_tests, cjson_utils_should_pass_json_patch_test_tests, compare_from_string, create_monitor, create_monitor_with_helpers, create_objects, do_test, file_test6_should_not_be_parsed, generate_merge_patch, generate_merge_tests, json_pointer_tests, LLVMFuzzerTestOneInput, main, merge_patch, merge_tests, misc_tests, overwrite_item, parse_array, parse_object, parse_with_opts_should_handle_null, parse_with_opts_should_parse_utf8_bom, parse_with_opts_should_require_null_if_requested, parse_with_opts_should_return_parse_end, reset, sort_tests, supports_full_hd, test12_should_not_be_parsed, test13_should_be_parsed_without_null_termination, test14_should_not_be_parsed, test_apply_patch, test_generate_test.
int cJSON_GetArraySize(const cJSON *array)
References cJSON::child, cJSON::next, size.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_GetArrayItem(const cJSON *array, int index)
References get_array_item.
Referenced by cjson_functions_should_not_crash_with_null_pointers, misc_tests.
cJSON* cJSON_GetObjectItem(const cJSON *const object, const char *const string)
References get_object_item.
Referenced by cJSON_DetachItemFromObject, cjson_functions_should_not_crash_with_null_pointers, cjson_get_object_item_should_get_object_items, cjson_get_object_item_should_not_crash_with_array, cJSON_HasObjectItem, cjson_set_valuestring_to_object_should_not_leak_memory, decode_patch_operation, json_pointer_tests.
cJSON* cJSON_GetObjectItemCaseSensitive(const cJSON *const object, const char *const string)
References get_object_item.
Referenced by cJSON_add_array_should_add_array, cjson_add_bool_should_add_bool, cjson_add_false_should_add_false, cjson_add_null_should_add_null, cjson_add_number_should_add_number, cJSON_add_object_should_add_object, cjson_add_raw_should_add_raw, cjson_add_string_should_add_string, cjson_add_true_should_add_true, cJSON_DetachItemFromObjectCaseSensitive, cjson_functions_should_not_crash_with_null_pointers, cjson_get_object_item_case_sensitive_should_get_object_items, cjson_get_object_item_case_sensitive_should_not_crash_with_array, decode_patch_operation, supports_full_hd, test_apply_patch, test_generate_test.
cJSON_bool cJSON_HasObjectItem(const cJSON *object, const char *string)
References cJSON_GetObjectItem.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
const char* cJSON_GetErrorPtr(void)
References global_error, error::json, error::position.
Referenced by file_test6_should_not_be_parsed, parse_with_opts_should_handle_empty_strings, parse_with_opts_should_handle_incomplete_json, supports_full_hd, test12_should_not_be_parsed.
char* cJSON_GetStringValue(const cJSON *const item)
References cJSON_IsString, item, cJSON::valuestring.
Referenced by cjson_get_string_value_should_get_a_string.
double cJSON_GetNumberValue(const cJSON *const item)
References cJSON_IsNumber, item, NAN, cJSON::valuedouble.
Referenced by cjson_get_number_value_should_get_a_number.
cJSON_bool cJSON_IsInvalid(const cJSON *const item)
References cJSON_Invalid, item, cJSON::type.
Referenced by cJSON_Compare, cjson_functions_should_not_crash_with_null_pointers, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsFalse(const cJSON *const item)
References cJSON_False, item, cJSON::type.
Referenced by cjson_functions_should_not_crash_with_null_pointers, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsTrue(const cJSON *const item)
References cJSON_True, item, cJSON::type.
Referenced by cjson_functions_should_not_crash_with_null_pointers, test_apply_patch, test_generate_test, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsBool(const cJSON *const item)
References cJSON_False, cJSON_True, item, cJSON::type.
Referenced by cjson_functions_should_not_crash_with_null_pointers, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsNull(const cJSON *const item)
References cJSON_NULL, item, cJSON::type.
Referenced by cjson_functions_should_not_crash_with_null_pointers, merge_patch, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsNumber(const cJSON *const item)
References cJSON_Number, item, cJSON::type.
Referenced by cjson_create_array_reference_should_create_an_array_reference, cjson_create_object_reference_should_create_an_object_reference, cjson_functions_should_not_crash_with_null_pointers, cJSON_GetNumberValue, supports_full_hd, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsString(const cJSON *const item)
References cJSON_String, item, cJSON::type.
Referenced by apply_patch, cjson_functions_should_not_crash_with_null_pointers, cJSON_GetStringValue, supports_full_hd, test_apply_patch, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsArray(const cJSON *const item)
References cJSON_Array, item, cJSON::type.
Referenced by apply_patch, cjson_create_array_reference_should_create_an_array_reference, cjson_functions_should_not_crash_with_null_pointers, cJSONUtils_ApplyPatches, cJSONUtils_ApplyPatchesCaseSensitive, cJSONUtils_FindPointerFromObjectTo, detach_path, get_item_from_pointer, parse_test_file, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsObject(const cJSON *const item)
References cJSON_Object, item, cJSON::type.
Referenced by apply_patch, cjson_create_object_reference_should_create_an_object_reference, cjson_functions_should_not_crash_with_null_pointers, cJSONUtils_FindPointerFromObjectTo, detach_path, generate_merge_patch, get_item_from_pointer, merge_patch, typecheck_functions_should_check_type.
cJSON_bool cJSON_IsRaw(const cJSON *const item)
References cJSON_Raw, item, cJSON::type.
Referenced by cjson_functions_should_not_crash_with_null_pointers, typecheck_functions_should_check_type.
cJSON* cJSON_CreateNull(void)
References cJSON_New_Item, cJSON_NULL, global_hooks, item, cJSON::type.
Referenced by cJSON_AddNullToObject, cjson_replace_item_via_pointer_should_replace_items, generate_merge_patch.
cJSON* cJSON_CreateTrue(void)
References cJSON_New_Item, cJSON_True, global_hooks, item, cJSON::type.
Referenced by cJSON_AddTrueToObject.
cJSON* cJSON_CreateFalse(void)
References cJSON_False, cJSON_New_Item, global_hooks, item, cJSON::type.
Referenced by cJSON_AddFalseToObject.
cJSON* cJSON_CreateBool(cJSON_bool boolean)
References cJSON_False, cJSON_New_Item, cJSON_True, global_hooks, item, cJSON::type.
Referenced by cJSON_AddBoolToObject.
cJSON* cJSON_CreateNumber(double num)
References cJSON_New_Item, cJSON_Number, global_hooks, item, cJSON::type, cJSON::valuedouble, cJSON::valueint.
Referenced by cjson_add_item_to_object_should_not_use_after_free_when_string_is_aliased, cJSON_AddNumberToObject, cjson_create_array_reference_should_create_an_array_reference, cjson_create_object_reference_should_create_an_object_reference, cJSON_CreateDoubleArray, cJSON_CreateFloatArray, cJSON_CreateIntArray, cjson_get_number_value_should_get_a_number, cjson_get_string_value_should_get_a_string, cjson_replace_item_in_object_should_preserve_name, create_monitor, sort_tests.
cJSON* cJSON_CreateString(const char *string)
References cJSON_Delete, cJSON_New_Item, cJSON_strdup, cJSON_String, global_hooks, item, cJSON::type, cJSON::valuestring.
Referenced by cJSON_AddStringToObject, cJSON_CreateStringArray, cjson_functions_should_not_crash_with_null_pointers, cjson_get_number_value_should_get_a_number, cjson_get_string_value_should_get_a_string, cjson_set_valuestring_to_object_should_not_leak_memory, cjson_utils_functions_shouldnt_crash_with_null_pointers, compose_patch, create_monitor, create_objects, misc_tests.
cJSON* cJSON_CreateRaw(const char *raw)
References cJSON_Delete, cJSON_New_Item, cJSON_Raw, cJSON_strdup, global_hooks, item, cJSON::type, cJSON::valuestring.
Referenced by cJSON_AddRawToObject, cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_CreateArray(void)
References cJSON_Array, cJSON_New_Item, global_hooks, item, cJSON::type.
Referenced by cjson_add_item_to_object_or_array_should_not_add_itself, cJSON_AddArrayToObject, cjson_create_array_reference_should_create_an_array_reference, cJSON_CreateDoubleArray, cJSON_CreateFloatArray, cJSON_CreateIntArray, cJSON_CreateStringArray, cjson_replace_item_via_pointer_should_replace_items, cJSONUtils_GeneratePatches, cJSONUtils_GeneratePatchesCaseSensitive, create_monitor, create_objects.
cJSON* cJSON_CreateObject(void)
References cJSON_New_Item, cJSON_Object, global_hooks, item, cJSON::type.
Referenced by cJSON_add_array_should_add_array, cjson_add_array_should_fail_on_allocation_failure, cjson_add_array_should_fail_with_null_pointers, cjson_add_bool_should_add_bool, cjson_add_bool_should_fail_on_allocation_failure, cjson_add_bool_should_fail_with_null_pointers, cjson_add_false_should_add_false, cjson_add_false_should_fail_on_allocation_failure, cjson_add_false_should_fail_with_null_pointers, cjson_add_item_to_object_or_array_should_not_add_itself, cjson_add_item_to_object_should_not_use_after_free_when_string_is_aliased, cjson_add_null_should_add_null, cjson_add_null_should_fail_on_allocation_failure, cjson_add_null_should_fail_with_null_pointers, cjson_add_number_should_add_number, cjson_add_number_should_fail_on_allocation_failure, cjson_add_number_should_fail_with_null_pointers, cJSON_add_object_should_add_object, cjson_add_object_should_fail_on_allocation_failure, cjson_add_object_should_fail_with_null_pointers, cjson_add_raw_should_add_raw, cjson_add_raw_should_fail_on_allocation_failure, cjson_add_raw_should_fail_with_null_pointers, cjson_add_string_should_add_string, cjson_add_string_should_fail_on_allocation_failure, cjson_add_string_should_fail_with_null_pointers, cjson_add_true_should_add_true, cjson_add_true_should_fail_on_allocation_failure, cjson_add_true_should_fail_with_null_pointers, cJSON_AddObjectToObject, cjson_create_object_reference_should_create_an_object_reference, compose_patch, create_monitor, create_monitor_with_helpers, create_objects, generate_merge_patch, merge_patch, misc_tests, sort_tests.
cJSON* cJSON_CreateStringReference(const char *string)
References cast_away_const, cJSON_IsReference, cJSON_New_Item, cJSON_String, global_hooks, item, cJSON::type, cJSON::valuestring.
Referenced by cjson_create_string_reference_should_create_a_string_reference, cjson_set_valuestring_to_object_should_not_leak_memory.
cJSON* cJSON_CreateObjectReference(const cJSON *child)
References cast_away_const, cJSON::child, cJSON_IsReference, cJSON_New_Item, cJSON_Object, global_hooks, item, cJSON::type.
Referenced by cjson_create_object_reference_should_create_an_object_reference.
cJSON* cJSON_CreateArrayReference(const cJSON *child)
References cast_away_const, cJSON::child, cJSON_Array, cJSON_IsReference, cJSON_New_Item, global_hooks, item, cJSON::type.
Referenced by cjson_create_array_reference_should_create_an_array_reference.
cJSON* cJSON_CreateIntArray(const int *numbers, int count)
References cJSON::child, cJSON_CreateArray, cJSON_CreateNumber, cJSON_Delete, count, cJSON::prev, suffix_object.
Referenced by cjson_create_int_array_should_fail_on_allocation_failure, cjson_functions_should_not_crash_with_null_pointers, create_objects, misc_tests.
cJSON* cJSON_CreateFloatArray(const float *numbers, int count)
References cJSON::child, cJSON_CreateArray, cJSON_CreateNumber, cJSON_Delete, count, cJSON::prev, suffix_object.
Referenced by cjson_create_float_array_should_fail_on_allocation_failure, cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_CreateDoubleArray(const double *numbers, int count)
References cJSON::child, cJSON_CreateArray, cJSON_CreateNumber, cJSON_Delete, count, cJSON::prev, suffix_object.
Referenced by cjson_create_double_array_should_fail_on_allocation_failure, cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_CreateStringArray(const char *const *strings, int count)
References cJSON::child, cJSON_CreateArray, cJSON_CreateString, cJSON_Delete, count, cJSON::prev, suffix_object.
Referenced by cjson_create_string_array_should_fail_on_allocation_failure, cjson_functions_should_not_crash_with_null_pointers, create_objects.
cJSON_bool cJSON_AddItemToArray(cJSON *array, cJSON *item)
References add_item_to_array, item.
Referenced by apply_patch, cjson_add_item_to_object_or_array_should_not_add_itself, cjson_create_array_reference_should_create_an_array_reference, cjson_delete_item_from_array_should_not_broken_list_structure, cjson_functions_should_not_crash_with_null_pointers, cjson_replace_item_via_pointer_should_replace_items, compose_patch, create_monitor, create_monitor_with_helpers, create_objects, insert_item_in_array.
cJSON_bool cJSON_AddItemToObject(cJSON *object, const char *string, cJSON *item)
References add_item_to_object, global_hooks, item.
Referenced by apply_patch, cjson_add_item_to_object_or_array_should_not_add_itself, cjson_add_item_to_object_should_not_use_after_free_when_string_is_aliased, cjson_functions_should_not_crash_with_null_pointers, cjson_replace_item_in_object_should_preserve_name, cjson_set_valuestring_to_object_should_not_leak_memory, compose_patch, create_monitor, create_objects, generate_merge_patch, merge_patch, misc_tests, sort_tests.
cJSON_bool cJSON_AddItemToObjectCS(cJSON *object, const char *string, cJSON *item)
References add_item_to_object, global_hooks, item.
Referenced by cjson_create_object_reference_should_create_an_object_reference, cjson_functions_should_not_crash_with_null_pointers.
cJSON_bool cJSON_AddItemReferenceToArray(cJSON *array, cJSON *item)
References add_item_to_array, create_reference, global_hooks, item.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
cJSON_bool cJSON_AddItemReferenceToObject(cJSON *object, const char *string, cJSON *item)
References add_item_to_object, create_reference, global_hooks, item.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_DetachItemViaPointer(cJSON *parent, cJSON *const item)
References cJSON::child, item, cJSON::next, cJSON::prev.
Referenced by cjson_detach_item_via_pointer_should_detach_items, cJSON_DetachItemFromArray, cJSON_DetachItemFromObject, cJSON_DetachItemFromObjectCaseSensitive, cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_DetachItemFromArray(cJSON *array, int which)
References cJSON_DetachItemViaPointer, get_array_item.
Referenced by cJSON_DeleteItemFromArray, cjson_functions_should_not_crash_with_null_pointers.
void cJSON_DeleteItemFromArray(cJSON *array, int which)
References cJSON_Delete, cJSON_DetachItemFromArray.
Referenced by cjson_delete_item_from_array_should_not_broken_list_structure, cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_DetachItemFromObject(cJSON *object, const char *string)
References cJSON_DetachItemViaPointer, cJSON_GetObjectItem.
Referenced by cJSON_DeleteItemFromObject, cjson_functions_should_not_crash_with_null_pointers, detach_path, merge_patch.
cJSON* cJSON_DetachItemFromObjectCaseSensitive(cJSON *object, const char *string)
References cJSON_DetachItemViaPointer, cJSON_GetObjectItemCaseSensitive.
Referenced by cJSON_DeleteItemFromObjectCaseSensitive, cjson_functions_should_not_crash_with_null_pointers, merge_patch.
void cJSON_DeleteItemFromObject(cJSON *object, const char *string)
References cJSON_Delete, cJSON_DetachItemFromObject.
Referenced by apply_patch, cjson_functions_should_not_crash_with_null_pointers, merge_patch.
void cJSON_DeleteItemFromObjectCaseSensitive(cJSON *object, const char *string)
References cJSON_Delete, cJSON_DetachItemFromObjectCaseSensitive.
Referenced by apply_patch, cjson_functions_should_not_crash_with_null_pointers, merge_patch.
cJSON_bool cJSON_InsertItemInArray(cJSON *array, int which, cJSON *newitem)
References add_item_to_array, cJSON::child, get_array_item, cJSON::next, cJSON::prev.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
cJSON_bool cJSON_ReplaceItemViaPointer(cJSON *const parent, cJSON *const item, cJSON *replacement)
References cJSON::child, cJSON_Delete, item, cJSON::next, cJSON::prev.
Referenced by cjson_functions_should_not_crash_with_null_pointers, cjson_replace_item_via_pointer_should_replace_items, cJSON_ReplaceItemInArray, replace_item_in_object.
cJSON_bool cJSON_ReplaceItemInArray(cJSON *array, int which, cJSON *newitem)
References cJSON_ReplaceItemViaPointer, get_array_item.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
cJSON_bool cJSON_ReplaceItemInObject(cJSON *object, const char *string, cJSON *newitem)
References replace_item_in_object.
Referenced by cjson_functions_should_not_crash_with_null_pointers, cjson_replace_item_in_object_should_preserve_name.
cJSON_bool cJSON_ReplaceItemInObjectCaseSensitive(cJSON *object, const char *string, cJSON *newitem)
References replace_item_in_object.
Referenced by cjson_functions_should_not_crash_with_null_pointers.
cJSON* cJSON_Duplicate(const cJSON *item, cJSON_bool recurse)
References cJSON::child, cJSON_Delete, cJSON_Duplicate, cJSON_IsReference, cJSON_New_Item, cJSON_strdup, cJSON_StringIsConst, global_hooks, item, cJSON::next, cJSON::prev, cJSON::string, cJSON::type, cJSON::valuedouble, cJSON::valueint, cJSON::valuestring.
Referenced by apply_patch, cJSON_Duplicate, cjson_functions_should_not_crash_with_null_pointers, compose_patch, generate_merge_patch, merge_patch, test_apply_patch, test_generate_test.
cJSON_bool cJSON_Compare(const cJSON *const a, const cJSON *const b, const cJSON_bool case_sensitive)
References cJSON::child, cJSON_Array, cJSON_ArrayForEach, cJSON_Compare, cJSON_False, cJSON_IsInvalid, cJSON_NULL, cJSON_Number, cJSON_Object, cJSON_Raw, cJSON_String, cJSON_True, compare_double, get_object_item, cJSON::next, cJSON::string, cJSON::type, cJSON::valuedouble, cJSON::valuestring.
Referenced by cJSON_Compare, cjson_compare_should_compare_invalid_as_not_equal, cjson_compare_should_compare_null_pointer_as_not_equal, cjson_compare_should_compare_raw, cjson_compare_should_not_accept_invalid_types, cjson_functions_should_not_crash_with_null_pointers, compare_from_string, parse_with_opts_should_parse_utf8_bom, test_apply_patch, test_generate_test.
void cJSON_Minify(char *json)
References json, minify_string, skip_multiline_comment, skip_oneline_comment.
Referenced by cjson_functions_should_not_crash_with_null_pointers, cjson_minify_should_minify_json, cjson_minify_should_not_loop_infinitely, cjson_minify_should_not_modify_strings, cjson_minify_should_not_overflow_buffer, cjson_minify_should_remove_multiline_comments, cjson_minify_should_remove_single_line_comments, cjson_minify_should_remove_spaces, LLVMFuzzerTestOneInput.
cJSON* cJSON_AddNullToObject(cJSON *const object, const char *const name)
References add_item_to_object, cJSON_CreateNull, cJSON_Delete, global_hooks, name.
Referenced by cjson_add_null_should_add_null, cjson_add_null_should_fail_on_allocation_failure, cjson_add_null_should_fail_with_null_pointers.
cJSON* cJSON_AddTrueToObject(cJSON *const object, const char *const name)
References add_item_to_object, cJSON_CreateTrue, cJSON_Delete, global_hooks, name.
Referenced by cjson_add_true_should_add_true, cjson_add_true_should_fail_on_allocation_failure, cjson_add_true_should_fail_with_null_pointers.
cJSON* cJSON_AddFalseToObject(cJSON *const object, const char *const name)
References add_item_to_object, cJSON_CreateFalse, cJSON_Delete, global_hooks, name.
Referenced by cjson_add_false_should_add_false, cjson_add_false_should_fail_on_allocation_failure, cjson_add_false_should_fail_with_null_pointers, create_objects.
cJSON* cJSON_AddBoolToObject(cJSON *const object, const char *const name, const cJSON_bool boolean)
References add_item_to_object, cJSON_CreateBool, cJSON_Delete, global_hooks, name.
Referenced by cjson_add_bool_should_add_bool, cjson_add_bool_should_fail_on_allocation_failure, cjson_add_bool_should_fail_with_null_pointers.
cJSON* cJSON_AddNumberToObject(cJSON *const object, const char *const name, const double number)
References add_item_to_object, cJSON_CreateNumber, cJSON_Delete, global_hooks, name.
Referenced by cjson_add_number_should_add_number, cjson_add_number_should_fail_on_allocation_failure, cjson_add_number_should_fail_with_null_pointers, create_monitor_with_helpers, create_objects.
cJSON* cJSON_AddStringToObject(cJSON *const object, const char *const name, const char *const string)
References add_item_to_object, cJSON_CreateString, cJSON_Delete, global_hooks, name.
Referenced by cjson_add_string_should_add_string, cjson_add_string_should_fail_on_allocation_failure, cjson_add_string_should_fail_with_null_pointers, create_monitor_with_helpers, create_objects.
cJSON* cJSON_AddRawToObject(cJSON *const object, const char *const name, const char *const raw)
References add_item_to_object, cJSON_CreateRaw, cJSON_Delete, global_hooks, name.
Referenced by cjson_add_raw_should_add_raw, cjson_add_raw_should_fail_on_allocation_failure, cjson_add_raw_should_fail_with_null_pointers.
cJSON* cJSON_AddObjectToObject(cJSON *const object, const char *const name)
References add_item_to_object, cJSON_CreateObject, cJSON_Delete, global_hooks, name.
Referenced by cJSON_add_object_should_add_object, cjson_add_object_should_fail_on_allocation_failure, cjson_add_object_should_fail_with_null_pointers.
cJSON* cJSON_AddArrayToObject(cJSON *const object, const char *const name)
References add_item_to_object, cJSON_CreateArray, cJSON_Delete, global_hooks, name.
Referenced by cJSON_add_array_should_add_array, cjson_add_array_should_fail_on_allocation_failure, cjson_add_array_should_fail_with_null_pointers, cjson_delete_item_from_array_should_not_broken_list_structure, create_monitor_with_helpers.
double cJSON_SetNumberHelper(cJSON *object, double number)
References cJSON::valuedouble, cJSON::valueint.
char* cJSON_SetValuestring(cJSON *object, const char *valuestring)
References cJSON_free, cJSON_IsReference, cJSON_strdup, cJSON_String, global_hooks, cJSON::type, cJSON::valuestring.
Referenced by cjson_set_valuestring_to_object_should_not_leak_memory.
void* cJSON_malloc(size_t size)
References internal_hooks::allocate, global_hooks, size.
Referenced by cJSONUtils_FindPointerFromObjectTo, cJSONUtils_strdup, compose_patch, create_patches.
void cJSON_free(void *object)
References internal_hooks::deallocate, global_hooks.
Referenced by apply_patch, cjson_replace_item_via_pointer_should_replace_items, cJSON_SetValuestring, cJSONUtils_FindPointerFromObjectTo, compose_patch, create_patches, detach_path, overwrite_item, replace_item_in_object.