cJSON_Utils.h
cJSON* cJSONUtils_GetPointer(cJSON *const object, const char *pointer)
References get_item_from_pointer.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers, json_pointer_tests.
cJSON* cJSONUtils_GetPointerCaseSensitive(cJSON *const object, const char *pointer)
References get_item_from_pointer.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers.
cJSON* cJSONUtils_GeneratePatches(cJSON *const from, cJSON *const to)
References cJSON_CreateArray, create_patches.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers.
cJSON* cJSONUtils_GeneratePatchesCaseSensitive(cJSON *const from, cJSON *const to)
References cJSON_CreateArray, create_patches.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers, test_generate_test.
void cJSONUtils_AddPatchToArray(cJSON *const array, const char *const operation, const char *const path, const cJSON *const value)
References compose_patch.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers.
int cJSONUtils_ApplyPatches(cJSON *const object, const cJSON *const patches)
References apply_patch, cJSON::child, cJSON_IsArray, cJSON::next.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers.
int cJSONUtils_ApplyPatchesCaseSensitive(cJSON *const object, const cJSON *const patches)
References apply_patch, cJSON::child, cJSON_IsArray, cJSON::next.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers, test_apply_patch, test_generate_test.
cJSON* cJSONUtils_MergePatch(cJSON *target, const cJSON *const patch)
References merge_patch.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers, generate_merge_tests, merge_tests.
cJSON* cJSONUtils_MergePatchCaseSensitive(cJSON *target, const cJSON *const patch)
References merge_patch.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers.
cJSON* cJSONUtils_GenerateMergePatch(cJSON *const from, cJSON *const to)
References generate_merge_patch.
Referenced by generate_merge_patch, generate_merge_tests.
cJSON* cJSONUtils_GenerateMergePatchCaseSensitive(cJSON *const from, cJSON *const to)
References generate_merge_patch.
char* cJSONUtils_FindPointerFromObjectTo(const cJSON *const object, const cJSON *const target)
References cJSON::child, cJSON_free, cJSON_IsArray, cJSON_IsObject, cJSON_malloc, cJSONUtils_FindPointerFromObjectTo, cJSONUtils_strdup, encode_string_as_pointer, cJSON::next, pointer_encoded_length, cJSON::string.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers, cJSONUtils_FindPointerFromObjectTo, misc_tests.
void cJSONUtils_SortObject(cJSON *const object)
References sort_object.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers, sort_tests.
void cJSONUtils_SortObjectCaseSensitive(cJSON *const object)
References sort_object.
Referenced by cjson_utils_functions_shouldnt_crash_with_null_pointers.