common.h
assert_has_type
assert_has_no_reference
assert_has_no_const_string
assert_has_valuestring
assert_has_no_valuestring
assert_has_string
assert_has_no_string
assert_not_in_list
assert_has_child
assert_has_no_child
assert_is_invalid
void reset(cJSON *item)
References cJSON::child, cJSON_Delete, internal_hooks::deallocate, global_hooks, cJSON::string, cJSON::type, cJSON::valuestring.
Referenced by assert_not_object, assert_print_array, assert_print_object, assert_print_value, parse_array_should_parse_arrays_with_multiple_elements, parse_array_should_parse_arrays_with_one_element, parse_object_should_parse_empty_objects, parse_object_should_parse_objects_with_multiple_elements, parse_object_should_parse_objects_with_one_element, parse_string_should_not_overflow_with_closing_backslash, parse_string_should_not_parse_invalid_backslash, parse_string_should_not_parse_non_strings, parse_string_should_parse_bug_94, parse_string_should_parse_strings, parse_string_should_parse_utf16_surrogate_pairs, parse_value_should_parse_array, parse_value_should_parse_false, parse_value_should_parse_null, parse_value_should_parse_number, parse_value_should_parse_object, parse_value_should_parse_string, parse_value_should_parse_true.
char * read_file(const char *filename)
Referenced by do_test, file_test6_should_not_be_parsed, parse_file, parse_test_file.