compare_tests.c
static cJSON_bool compare_from_string(const char *const a, const char *const b, const cJSON_bool case_sensitive)
References cJSON_Compare, cJSON_Delete, cJSON_Parse.
Referenced by cjson_compare_should_compare_arrays, cjson_compare_should_compare_booleans, cjson_compare_should_compare_null, cjson_compare_should_compare_numbers, cjson_compare_should_compare_objects, cjson_compare_should_compare_strings.
static void cjson_compare_should_compare_null_pointer_as_not_equal(void)
References cJSON_Compare.
Referenced by main.
static void cjson_compare_should_compare_invalid_as_not_equal(void)
References cJSON_Compare.
Referenced by main.
static void cjson_compare_should_compare_numbers(void)
References compare_from_string.
Referenced by main.
static void cjson_compare_should_compare_booleans(void)
References compare_from_string.
Referenced by main.
static void cjson_compare_should_compare_null(void)
References compare_from_string.
Referenced by main.
static void cjson_compare_should_not_accept_invalid_types(void)
References cJSON_Compare, cJSON::type.
Referenced by main.
static void cjson_compare_should_compare_strings(void)
References compare_from_string.
Referenced by main.
static void cjson_compare_should_compare_raw(void)
References cJSON_Compare, cJSON_Delete, cJSON_Parse, cJSON::type.
Referenced by main.
static void cjson_compare_should_compare_arrays(void)
References compare_from_string.
Referenced by main.
static void cjson_compare_should_compare_objects(void)
References compare_from_string.
Referenced by main.
int main(void)
References cjson_compare_should_compare_arrays, cjson_compare_should_compare_booleans, cjson_compare_should_compare_invalid_as_not_equal, cjson_compare_should_compare_null, cjson_compare_should_compare_null_pointer_as_not_equal, cjson_compare_should_compare_numbers, cjson_compare_should_compare_objects, cjson_compare_should_compare_raw, cjson_compare_should_compare_strings, cjson_compare_should_not_accept_invalid_types.