TestProductionCode_Runner.c
RUN_TEST
void setUp(void)
void tearDown(void)
void test_FindFunction_WhichIsBroken_ShouldReturnZeroIfItemIsNotInList_WhichWorksEvenInOurBrokenCode(void)
References FindFunction_WhichIsBroken.
Referenced by main.
void test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken(void)
References FindFunction_WhichIsBroken.
Referenced by main.
void test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValue(void)
References Counter, FunctionWhichReturnsLocalVariable.
Referenced by main.
void test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValueAgain(void)
References FunctionWhichReturnsLocalVariable.
Referenced by main.
void test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed(void)
References FunctionWhichReturnsLocalVariable.
Referenced by main.
void resetTest(void)
References setUp, tearDown.
int main(void)
References test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken, test_FindFunction_WhichIsBroken_ShouldReturnZeroIfItemIsNotInList_WhichWorksEvenInOurBrokenCode, test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed, test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValue, test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValueAgain, UnityBegin, UnityEnd.