ProductionCode.h
int FindFunction_WhichIsBroken(int NumberToFind)
References NumbersToFind.
Referenced by TEST, test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken, test_FindFunction_WhichIsBroken_ShouldReturnZeroIfItemIsNotInList_WhichWorksEvenInOurBrokenCode.
int FunctionWhichReturnsLocalVariable(void)
References Counter.
Referenced by TEST, test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed, test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValue, test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValueAgain.