TestProductionCode2_Runner.c
RUN_TEST
void setUp(void)
void tearDown(void)
void test_IgnoredTest(void)
Referenced by main.
void test_AnotherIgnoredTest(void)
Referenced by main.
void test_ThisFunctionHasNotBeenTested_NeedsToBeImplemented(void)
Referenced by main.
void resetTest(void)
References setUp, tearDown.
int main(void)
References test_AnotherIgnoredTest, test_IgnoredTest, test_ThisFunctionHasNotBeenTested_NeedsToBeImplemented, UnityBegin, UnityEnd.