TestProductionCode.c
int Counter
Referenced by FunctionWhichReturnsLocalVariable, setUp, TEST, test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValue, TEST_SETUP.
void setUp(void)
References Counter.
void tearDown(void)
void test_FindFunction_WhichIsBroken_ShouldReturnZeroIfItemIsNotInList_WhichWorksEvenInOurBrokenCode(void)
References FindFunction_WhichIsBroken, TEST_ASSERT_EQUAL.
Referenced by main.
void test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken(void)
References FindFunction_WhichIsBroken, TEST_ASSERT_EQUAL.
Referenced by main.
void test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValue(void)
References Counter, FunctionWhichReturnsLocalVariable, TEST_ASSERT_EQUAL_HEX.
Referenced by main.
void test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValueAgain(void)
References FunctionWhichReturnsLocalVariable, TEST_ASSERT_EQUAL_HEX.
Referenced by main.
void test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed(void)
References FunctionWhichReturnsLocalVariable, TEST_ASSERT_EQUAL_HEX.
Referenced by main.