json_patch_tests.c
static cJSON* parse_test_file(const char *const filename)
References cJSON_IsArray, cJSON_Parse, read_file.
Referenced by cjson_utils_should_pass_json_patch_test_cjson_utils_tests, cjson_utils_should_pass_json_patch_test_spec_tests, cjson_utils_should_pass_json_patch_test_tests.
static cJSON_bool test_apply_patch(const cJSON *const test)
References cJSON_Compare, cJSON_Delete, cJSON_Duplicate, cJSON_GetObjectItemCaseSensitive, cJSON_IsString, cJSON_IsTrue, cJSONUtils_ApplyPatchesCaseSensitive, cJSON::valuestring.
Referenced by cjson_utils_should_pass_json_patch_test_cjson_utils_tests, cjson_utils_should_pass_json_patch_test_spec_tests, cjson_utils_should_pass_json_patch_test_tests.
static cJSON_bool test_generate_test(cJSON *test)
References cJSON_Compare, cJSON_Delete, cJSON_Duplicate, cJSON_GetObjectItemCaseSensitive, cJSON_IsTrue, cJSON_Print, cJSONUtils_ApplyPatchesCaseSensitive, cJSONUtils_GeneratePatchesCaseSensitive.
Referenced by cjson_utils_should_pass_json_patch_test_cjson_utils_tests, cjson_utils_should_pass_json_patch_test_spec_tests, cjson_utils_should_pass_json_patch_test_tests.
static void cjson_utils_should_pass_json_patch_test_tests(void)
References cJSON_Delete, parse_test_file, test_apply_patch, test_generate_test.
Referenced by main.
static void cjson_utils_should_pass_json_patch_test_spec_tests(void)
References cJSON_Delete, parse_test_file, test_apply_patch, test_generate_test.
Referenced by main.
static void cjson_utils_should_pass_json_patch_test_cjson_utils_tests(void)
References cJSON_Delete, parse_test_file, test_apply_patch, test_generate_test.
Referenced by main.
int main(void)
References cjson_utils_should_pass_json_patch_test_cjson_utils_tests, cjson_utils_should_pass_json_patch_test_spec_tests, cjson_utils_should_pass_json_patch_test_tests.