minify_tests.c
static void cjson_minify_should_not_overflow_buffer(void)
References cJSON_Minify.
Referenced by main.
static void cjson_minify_should_remove_single_line_comments(void)
References cJSON_Minify.
Referenced by main.
static void cjson_minify_should_remove_spaces(void)
References cJSON_Minify.
Referenced by main.
static void cjson_minify_should_remove_multiline_comments(void)
References cJSON_Minify.
Referenced by main.
static void cjson_minify_should_not_modify_strings(void)
References cJSON_Minify.
Referenced by main.
static void cjson_minify_should_minify_json(void)
References cJSON_Minify.
Referenced by main.
static void cjson_minify_should_not_loop_infinitely(void)
References cJSON_Minify.
Referenced by main.
int main(void)
References cjson_minify_should_minify_json, cjson_minify_should_not_loop_infinitely, cjson_minify_should_not_modify_strings, cjson_minify_should_not_overflow_buffer, cjson_minify_should_remove_multiline_comments, cjson_minify_should_remove_single_line_comments, cjson_minify_should_remove_spaces.