misc_tests.c
static void cjson_array_foreach_should_loop_over_arrays(void)
References cJSON::child, cJSON::next, cJSON::prev.
Referenced by main.
static void cjson_array_foreach_should_not_dereference_null_pointer(void)
Referenced by main.
static void cjson_get_object_item_should_get_object_items(void)
References cJSON_Delete, cJSON_GetObjectItem, cJSON_Parse, cJSON::valuedouble.
Referenced by main.
static void cjson_get_object_item_case_sensitive_should_get_object_items(void)
References cJSON_Delete, cJSON_GetObjectItemCaseSensitive, cJSON_Parse, cJSON::valuedouble.
Referenced by main.
static void cjson_get_object_item_should_not_crash_with_array(void)
References cJSON_Delete, cJSON_GetObjectItem, cJSON_Parse.
Referenced by main.
static void cjson_get_object_item_case_sensitive_should_not_crash_with_array(void)
References cJSON_Delete, cJSON_GetObjectItemCaseSensitive, cJSON_Parse.
Referenced by main.
static void typecheck_functions_should_check_type(void)
References cJSON_IsArray, cJSON_IsBool, cJSON_IsFalse, cJSON_IsInvalid, cJSON_IsNull, cJSON_IsNumber, cJSON_IsObject, cJSON_IsRaw, cJSON_IsString, cJSON_IsTrue, cJSON::type.
Referenced by main.
static void cjson_should_not_parse_to_deeply_nested_jsons(void)
References cJSON_Parse.
Referenced by main.
static void cjson_set_number_value_should_set_numbers(void)
References cJSON::valuedouble, cJSON::valueint.
Referenced by main.
static void cjson_detach_item_via_pointer_should_detach_items(void)
References cJSON::child, cJSON_DetachItemViaPointer, cJSON::next, cJSON::prev.
Referenced by main.
static void cjson_replace_item_via_pointer_should_replace_items(void)
References cJSON::child, cJSON_AddItemToArray, cJSON_CreateArray, cJSON_CreateNull, cJSON_free, cJSON_ReplaceItemViaPointer, cJSON::next, cJSON::prev.
Referenced by main.
static void cjson_replace_item_in_object_should_preserve_name(void)
References cJSON::child, cJSON_AddItemToObject, cJSON_CreateNumber, cJSON_Delete, cJSON_ReplaceItemInObject, cJSON::string.
Referenced by main.
static void cjson_functions_should_not_crash_with_null_pointers(void)
References cJSON_AddItemReferenceToArray, cJSON_AddItemReferenceToObject, cJSON_AddItemToArray, cJSON_AddItemToObject, cJSON_AddItemToObjectCS, cJSON_Compare, cJSON_CreateDoubleArray, cJSON_CreateFloatArray, cJSON_CreateIntArray, cJSON_CreateRaw, cJSON_CreateString, cJSON_CreateStringArray, cJSON_Delete, cJSON_DeleteItemFromArray, cJSON_DeleteItemFromObject, cJSON_DeleteItemFromObjectCaseSensitive, cJSON_DetachItemFromArray, cJSON_DetachItemFromObject, cJSON_DetachItemFromObjectCaseSensitive, cJSON_DetachItemViaPointer, cJSON_Duplicate, cJSON_GetArrayItem, cJSON_GetArraySize, cJSON_GetObjectItem, cJSON_GetObjectItemCaseSensitive, cJSON_HasObjectItem, cJSON_InitHooks, cJSON_InsertItemInArray, cJSON_IsArray, cJSON_IsBool, cJSON_IsFalse, cJSON_IsInvalid, cJSON_IsNull, cJSON_IsNumber, cJSON_IsObject, cJSON_IsRaw, cJSON_IsString, cJSON_IsTrue, cJSON_Minify, cJSON_Parse, cJSON_ParseWithOpts, cJSON_Print, cJSON_PrintBuffered, cJSON_PrintPreallocated, cJSON_PrintUnformatted, cJSON_ReplaceItemInArray, cJSON_ReplaceItemInObject, cJSON_ReplaceItemInObjectCaseSensitive, cJSON_ReplaceItemViaPointer.
Referenced by main.
static void* failing_realloc(void *pointer, size_t size)
Referenced by ensure_should_fail_on_failed_realloc.
static void ensure_should_fail_on_failed_realloc(void)
References printbuffer::buffer, ensure, failing_realloc.
Referenced by main.
static void skip_utf8_bom_should_skip_bom(void)
References parse_buffer::content, global_hooks, parse_buffer::hooks, parse_buffer::length, parse_buffer::offset, skip_utf8_bom.
Referenced by main.
static void skip_utf8_bom_should_not_skip_bom_if_not_at_beginning(void)
References parse_buffer::content, global_hooks, parse_buffer::hooks, parse_buffer::length, parse_buffer::offset, skip_utf8_bom.
Referenced by main.
static void cjson_get_string_value_should_get_a_string(void)
References cJSON_CreateNumber, cJSON_CreateString, cJSON_Delete, cJSON_GetStringValue, cJSON::valuestring.
Referenced by main.
static void cjson_get_number_value_should_get_a_number(void)
References cJSON_CreateNumber, cJSON_CreateString, cJSON_Delete, cJSON_GetNumberValue, cJSON::valuedouble.
Referenced by main.
static void cjson_create_string_reference_should_create_a_string_reference(void)
References cJSON_CreateStringReference, cJSON_Delete, cJSON::type, cJSON::valuestring.
Referenced by main.
static void cjson_create_object_reference_should_create_an_object_reference(void)
References cJSON::child, cJSON_AddItemToObjectCS, cJSON_CreateNumber, cJSON_CreateObject, cJSON_CreateObjectReference, cJSON_Delete, cJSON_IsNumber, cJSON_IsObject, cJSON::type.
Referenced by main.
static void cjson_create_array_reference_should_create_an_array_reference(void)
References cJSON::child, cJSON_AddItemToArray, cJSON_CreateArray, cJSON_CreateArrayReference, cJSON_CreateNumber, cJSON_Delete, cJSON_IsArray, cJSON_IsNumber, cJSON::type.
Referenced by main.
static void cjson_add_item_to_object_or_array_should_not_add_itself(void)
References cJSON_AddItemToArray, cJSON_AddItemToObject, cJSON_CreateArray, cJSON_CreateObject, cJSON_Delete.
Referenced by main.
static void cjson_add_item_to_object_should_not_use_after_free_when_string_is_aliased(void)
References cJSON_AddItemToObject, cJSON_CreateNumber, cJSON_CreateObject, cJSON_Delete, cJSON_strdup, global_hooks, cJSON::string.
Referenced by main.
static void cjson_delete_item_from_array_should_not_broken_list_structure(void)
References cJSON_AddArrayToObject, cJSON_AddItemToArray, cJSON_Delete, cJSON_DeleteItemFromArray, cJSON_Parse, cJSON_PrintUnformatted.
Referenced by main.
static void cjson_set_valuestring_to_object_should_not_leak_memory(void)
References cJSON_AddItemToObject, cJSON_CreateString, cJSON_CreateStringReference, cJSON_Delete, cJSON_GetObjectItem, cJSON_Parse, cJSON_SetValuestring, cJSON::valuestring.
Referenced by main.
int main(void)
References cjson_add_item_to_object_or_array_should_not_add_itself, cjson_add_item_to_object_should_not_use_after_free_when_string_is_aliased, cjson_array_foreach_should_loop_over_arrays, cjson_array_foreach_should_not_dereference_null_pointer, cjson_create_array_reference_should_create_an_array_reference, cjson_create_object_reference_should_create_an_object_reference, cjson_create_string_reference_should_create_a_string_reference, cjson_delete_item_from_array_should_not_broken_list_structure, cjson_detach_item_via_pointer_should_detach_items, cjson_functions_should_not_crash_with_null_pointers, cjson_get_number_value_should_get_a_number, cjson_get_object_item_case_sensitive_should_get_object_items, cjson_get_object_item_case_sensitive_should_not_crash_with_array, cjson_get_object_item_should_get_object_items, cjson_get_object_item_should_not_crash_with_array, cjson_get_string_value_should_get_a_string, cjson_replace_item_in_object_should_preserve_name, cjson_replace_item_via_pointer_should_replace_items, cjson_set_number_value_should_set_numbers, cjson_set_valuestring_to_object_should_not_leak_memory, cjson_should_not_parse_to_deeply_nested_jsons, ensure_should_fail_on_failed_realloc, skip_utf8_bom_should_not_skip_bom_if_not_at_beginning, skip_utf8_bom_should_skip_bom, typecheck_functions_should_check_type.