old_utils_tests.c
const char* merges[15][3][15][3]
Referenced by generate_merge_tests, merge_tests.
static void json_pointer_tests(void)
References cJSON::child, cJSON_Delete, cJSON_GetObjectItem, cJSON_Parse, cJSONUtils_GetPointer.
Referenced by main.
static void misc_tests(void)
References cJSON_AddItemToObject, cJSON_CreateIntArray, cJSON_CreateObject, cJSON_CreateString, cJSON_Delete, cJSON_GetArrayItem, cJSONUtils_FindPointerFromObjectTo.
Referenced by main.
static void sort_tests(void)
References cJSON::child, cJSON_AddItemToObject, cJSON_CreateNumber, cJSON_CreateObject, cJSON_Delete, cJSONUtils_SortObject, cJSON::next, cJSON::prev, cJSON::string.
Referenced by main.
static void merge_tests(void)
References cJSON_Delete, cJSON_Parse, cJSON_PrintUnformatted, cJSONUtils_MergePatch, merges.
Referenced by main.
static void generate_merge_tests(void)
References cJSON_Delete, cJSON_Parse, cJSON_PrintUnformatted, cJSONUtils_GenerateMergePatch, cJSONUtils_MergePatch, merges.
Referenced by main.
int main(void)
References generate_merge_tests, json_pointer_tests, merge_tests, misc_tests, sort_tests.