parse_string.c
cJSON item[1][1]
Referenced by assert_not_parse_string, assert_parse_string, main, parse_string_should_not_overflow_with_closing_backslash, parse_string_should_not_parse_invalid_backslash, parse_string_should_not_parse_non_strings, parse_string_should_parse_bug_94, parse_string_should_parse_strings, parse_string_should_parse_utf16_surrogate_pairs.
static void assert_is_string(cJSON *string_item)
Referenced by assert_parse_string.
static void assert_parse_string(const char *string, const char *expected)
References assert_is_string, parse_buffer::content, internal_hooks::deallocate, global_hooks, parse_buffer::hooks, item, parse_buffer::length, parse_string, cJSON::valuestring.
Referenced by parse_string_should_parse_bug_94, parse_string_should_parse_strings, parse_string_should_parse_utf16_surrogate_pairs.
static void assert_not_parse_string(const char *const string)
References parse_buffer::content, global_hooks, parse_buffer::hooks, item, parse_buffer::length, parse_string.
Referenced by parse_string_should_not_overflow_with_closing_backslash, parse_string_should_not_parse_invalid_backslash, parse_string_should_not_parse_non_strings.
static void parse_string_should_parse_strings(void)
References assert_parse_string, item, reset.
Referenced by main.
static void parse_string_should_parse_utf16_surrogate_pairs(void)
References assert_parse_string, item, reset.
Referenced by main.
static void parse_string_should_not_parse_non_strings(void)
References assert_not_parse_string, item, reset.
Referenced by main.
static void parse_string_should_not_parse_invalid_backslash(void)
References assert_not_parse_string, item, reset.
Referenced by main.
static void parse_string_should_not_overflow_with_closing_backslash(void)
References assert_not_parse_string, item, reset.
Referenced by main.
static void parse_string_should_parse_bug_94(void)
References assert_parse_string, item, reset.
Referenced by main.
int main(void)
References item, parse_string_should_not_overflow_with_closing_backslash, parse_string_should_not_parse_invalid_backslash, parse_string_should_not_parse_non_strings, parse_string_should_parse_bug_94, parse_string_should_parse_strings, parse_string_should_parse_utf16_surrogate_pairs.