parse_with_opts.c
static void parse_with_opts_should_handle_null(void)
References cJSON_Delete, cJSON_ParseWithOpts.
Referenced by main.
static void parse_with_opts_should_handle_empty_strings(void)
References cJSON_GetErrorPtr, cJSON_ParseWithOpts.
Referenced by main.
static void parse_with_opts_should_handle_incomplete_json(void)
References cJSON_GetErrorPtr, cJSON_ParseWithOpts.
Referenced by main.
static void parse_with_opts_should_require_null_if_requested(void)
References cJSON_Delete, cJSON_ParseWithOpts.
Referenced by main.
static void parse_with_opts_should_return_parse_end(void)
References cJSON_Delete, cJSON_ParseWithOpts.
Referenced by main.
static void parse_with_opts_should_parse_utf8_bom(void)
References cJSON_Compare, cJSON_Delete, cJSON_ParseWithOpts.
Referenced by main.
int main(void)
References parse_with_opts_should_handle_empty_strings, parse_with_opts_should_handle_incomplete_json, parse_with_opts_should_handle_null, parse_with_opts_should_parse_utf8_bom, parse_with_opts_should_require_null_if_requested, parse_with_opts_should_return_parse_end.