parse_object.c
cJSON item[1][1]
Referenced by assert_not_object, assert_parse_object, main, parse_object_should_parse_empty_objects, parse_object_should_parse_objects_with_multiple_elements, parse_object_should_parse_objects_with_one_element.
static void assert_is_object(cJSON *object_item)
Referenced by assert_parse_object.
static void assert_is_child(cJSON *child_item, const char *name, int type)
References cJSON::string, cJSON::type.
Referenced by parse_object_should_parse_objects_with_multiple_elements, parse_object_should_parse_objects_with_one_element.
static void assert_not_object(const char *json)
References parse_buffer::content, global_hooks, parse_buffer::hooks, item, parse_buffer::length, parse_object, reset.
Referenced by parse_object_should_not_parse_non_objects.
static void assert_parse_object(const char *json)
References assert_is_object, parse_buffer::content, global_hooks, parse_buffer::hooks, item, parse_buffer::length, parse_object.
Referenced by parse_object_should_parse_empty_objects, parse_object_should_parse_objects_with_multiple_elements, parse_object_should_parse_objects_with_one_element.
static void parse_object_should_parse_empty_objects(void)
References assert_parse_object, item, reset.
Referenced by main.
static void parse_object_should_parse_objects_with_one_element(void)
References assert_is_child, assert_parse_object, cJSON::child, item, reset.
Referenced by main.
static void parse_object_should_parse_objects_with_multiple_elements(void)
References assert_is_child, assert_parse_object, cJSON::child, item, cJSON::next, reset.
Referenced by main.
static void parse_object_should_not_parse_non_objects(void)
References assert_not_object.
Referenced by main.
int main(void)
References item, parse_object_should_not_parse_non_objects, parse_object_should_parse_empty_objects, parse_object_should_parse_objects_with_multiple_elements, parse_object_should_parse_objects_with_one_element.