parse_examples.c
TEST_DIR_PATH
static cJSON* parse_file(const char *filename)
References cJSON_Parse, read_file.
Referenced by do_test.
static void do_test(const char *test_name)
References cJSON_Delete, cJSON_Print, parse_file, read_file.
Referenced by file_test10_should_be_parsed_and_printed, file_test11_should_be_parsed_and_printed, file_test1_should_be_parsed_and_printed, file_test2_should_be_parsed_and_printed, file_test3_should_be_parsed_and_printed, file_test4_should_be_parsed_and_printed, file_test5_should_be_parsed_and_printed, file_test7_should_be_parsed_and_printed, file_test8_should_be_parsed_and_printed, file_test9_should_be_parsed_and_printed.
static void file_test1_should_be_parsed_and_printed(void)
References do_test.
Referenced by main.
static void file_test2_should_be_parsed_and_printed(void)
References do_test.
Referenced by main.
static void file_test3_should_be_parsed_and_printed(void)
References do_test.
Referenced by main.
static void file_test4_should_be_parsed_and_printed(void)
References do_test.
Referenced by main.
static void file_test5_should_be_parsed_and_printed(void)
References do_test.
Referenced by main.
static void file_test6_should_not_be_parsed(void)
References cJSON_Delete, cJSON_GetErrorPtr, cJSON_Parse, read_file.
Referenced by main.
static void file_test7_should_be_parsed_and_printed(void)
References do_test.
Referenced by main.
static void file_test8_should_be_parsed_and_printed(void)
References do_test.
Referenced by main.
static void file_test9_should_be_parsed_and_printed(void)
References do_test.
Referenced by main.
static void file_test10_should_be_parsed_and_printed(void)
References do_test.
Referenced by main.
static void file_test11_should_be_parsed_and_printed(void)
References do_test.
Referenced by main.
static void test12_should_not_be_parsed(void)
References cJSON_Delete, cJSON_GetErrorPtr, cJSON_Parse.
Referenced by main.
static void test13_should_be_parsed_without_null_termination(void)
References cJSON_Delete, cJSON_ParseWithLength.
Referenced by main.
static void test14_should_not_be_parsed(void)
References cJSON_Delete, cJSON_ParseWithLength.
Referenced by main.
int main(void)
References file_test10_should_be_parsed_and_printed, file_test11_should_be_parsed_and_printed, file_test1_should_be_parsed_and_printed, file_test2_should_be_parsed_and_printed, file_test3_should_be_parsed_and_printed, file_test4_should_be_parsed_and_printed, file_test5_should_be_parsed_and_printed, file_test6_should_not_be_parsed, file_test7_should_be_parsed_and_printed, file_test8_should_be_parsed_and_printed, file_test9_should_be_parsed_and_printed, test12_should_not_be_parsed, test13_should_be_parsed_without_null_termination, test14_should_not_be_parsed.