parse_number.c
cJSON item[1][1]
Referenced by assert_parse_number, main.
static void assert_is_number(cJSON *number_item)
Referenced by assert_parse_number.
static void assert_parse_number(const char *string, int integer, double real)
References assert_is_number, parse_buffer::content, item, parse_buffer::length, parse_number, cJSON::valuedouble, cJSON::valueint.
Referenced by parse_number_should_parse_negative_integers, parse_number_should_parse_negative_reals, parse_number_should_parse_positive_integers, parse_number_should_parse_positive_reals, parse_number_should_parse_zero.
static void parse_number_should_parse_zero(void)
References assert_parse_number.
Referenced by main.
static void parse_number_should_parse_negative_integers(void)
References assert_parse_number.
Referenced by main.
static void parse_number_should_parse_positive_integers(void)
References assert_parse_number.
Referenced by main.
static void parse_number_should_parse_positive_reals(void)
References assert_parse_number.
Referenced by main.
static void parse_number_should_parse_negative_reals(void)
References assert_parse_number.
Referenced by main.
int main(void)
References item, parse_number_should_parse_negative_integers, parse_number_should_parse_negative_reals, parse_number_should_parse_positive_integers, parse_number_should_parse_positive_reals, parse_number_should_parse_zero.