parse_array.c
cJSON item[1][1]
Referenced by add_item_to_array, add_item_to_object, assert_not_array, assert_parse_array, cJSON_AddItemReferenceToArray, cJSON_AddItemReferenceToObject, cJSON_AddItemToArray, cJSON_AddItemToObject, cJSON_AddItemToObjectCS, cJSON_CreateArray, cJSON_CreateArrayReference, cJSON_CreateBool, cJSON_CreateFalse, cJSON_CreateNull, cJSON_CreateNumber, cJSON_CreateObject, cJSON_CreateObjectReference, cJSON_CreateRaw, cJSON_CreateString, cJSON_CreateStringReference, cJSON_CreateTrue, cJSON_Delete, cJSON_DetachItemViaPointer, cJSON_Duplicate, cjson_functions_should_not_crash_with_null_pointers, cjson_get_object_item_case_sensitive_should_get_object_items, cjson_get_object_item_should_get_object_items, cJSON_GetNumberValue, cJSON_GetStringValue, cJSON_IsArray, cJSON_IsBool, cJSON_IsFalse, cJSON_IsInvalid, cJSON_IsNull, cJSON_IsNumber, cJSON_IsObject, cJSON_IsRaw, cJSON_IsString, cJSON_IsTrue, cJSON_ParseWithLengthOpts, cJSON_Print, cJSON_PrintBuffered, cJSON_PrintPreallocated, cJSON_PrintUnformatted, cJSON_ReplaceItemViaPointer, cjson_utils_functions_shouldnt_crash_with_null_pointers, create_reference, get_array_item, main, parse_array, parse_array_should_parse_arrays_with_multiple_elements, parse_array_should_parse_arrays_with_one_element, parse_array_should_parse_empty_arrays, parse_number, parse_object, parse_string, parse_value, print, print_array, print_number, print_object, print_string, print_value, reset, suffix_object, typecheck_functions_should_check_type.
static void assert_is_array(cJSON *array_item)
Referenced by assert_parse_array.
static void assert_not_array(const char *json)
References parse_buffer::content, global_hooks, parse_buffer::hooks, item, parse_buffer::length, parse_array.
Referenced by parse_array_should_not_parse_non_arrays.
static void assert_parse_array(const char *json)
References assert_is_array, parse_buffer::content, global_hooks, parse_buffer::hooks, item, parse_buffer::length, parse_array.
Referenced by parse_array_should_parse_arrays_with_multiple_elements, parse_array_should_parse_arrays_with_one_element, parse_array_should_parse_empty_arrays.
static void parse_array_should_parse_empty_arrays(void)
References assert_parse_array, item.
Referenced by main.
static void parse_array_should_parse_arrays_with_one_element(void)
References assert_parse_array, cJSON::child, item, reset, cJSON::valuestring.
Referenced by main.
static void parse_array_should_parse_arrays_with_multiple_elements(void)
References assert_parse_array, cJSON::child, item, cJSON::next, reset, cJSON::type.
Referenced by main.
static void parse_array_should_not_parse_non_arrays(void)
References assert_not_array.
Referenced by main.
int main(void)
References item, parse_array_should_not_parse_non_arrays, parse_array_should_parse_arrays_with_multiple_elements, parse_array_should_parse_arrays_with_one_element, parse_array_should_parse_empty_arrays.