parse_value.c
cJSON item[1][1]
Referenced by assert_parse_value, main, parse_value_should_parse_array, parse_value_should_parse_false, parse_value_should_parse_null, parse_value_should_parse_number, parse_value_should_parse_object, parse_value_should_parse_string, parse_value_should_parse_true.
static void assert_is_value(cJSON *value_item, int type)
Referenced by assert_parse_value.
static void assert_parse_value(const char *string, int type)
References assert_is_value, parse_buffer::content, global_hooks, parse_buffer::hooks, item, parse_buffer::length, parse_value.
Referenced by parse_value_should_parse_array, parse_value_should_parse_false, parse_value_should_parse_null, parse_value_should_parse_number, parse_value_should_parse_object, parse_value_should_parse_string, parse_value_should_parse_true.
static void parse_value_should_parse_null(void)
References assert_parse_value, item, reset.
Referenced by main.
static void parse_value_should_parse_true(void)
References assert_parse_value, item, reset.
Referenced by main.
static void parse_value_should_parse_false(void)
References assert_parse_value, item, reset.
Referenced by main.
static void parse_value_should_parse_number(void)
References assert_parse_value, item, reset.
Referenced by main.
static void parse_value_should_parse_string(void)
References assert_parse_value, item, reset.
Referenced by main.
static void parse_value_should_parse_array(void)
References assert_parse_value, item, reset.
Referenced by main.
static void parse_value_should_parse_object(void)
References assert_parse_value, item, reset.
Referenced by main.
int main(void)
References item, parse_value_should_parse_array, parse_value_should_parse_false, parse_value_should_parse_null, parse_value_should_parse_number, parse_value_should_parse_object, parse_value_should_parse_string, parse_value_should_parse_true.