print_number.c
static void assert_print_number(const char *expected, double input)
References printbuffer::buffer, global_hooks, printbuffer::hooks, printbuffer::length, printbuffer::noalloc, printbuffer::offset, print_number.
Referenced by print_number_should_print_negative_integers, print_number_should_print_negative_reals, print_number_should_print_positive_integers, print_number_should_print_positive_reals, print_number_should_print_zero.
static void print_number_should_print_zero(void)
References assert_print_number.
Referenced by main.
static void print_number_should_print_negative_integers(void)
References assert_print_number.
Referenced by main.
static void print_number_should_print_positive_integers(void)
References assert_print_number.
Referenced by main.
static void print_number_should_print_positive_reals(void)
References assert_print_number.
Referenced by main.
static void print_number_should_print_negative_reals(void)
References assert_print_number.
Referenced by main.
static void print_number_should_print_non_number(void)
Referenced by main.
int main(void)
References print_number_should_print_negative_integers, print_number_should_print_negative_reals, print_number_should_print_non_number, print_number_should_print_positive_integers, print_number_should_print_positive_reals, print_number_should_print_zero.