print_object.c
static void assert_print_object(const char *const expected, const char *const input)
References printbuffer::buffer, parse_buffer::content, printbuffer::format, global_hooks, parse_buffer::hooks, printbuffer::hooks, parse_buffer::length, printbuffer::length, printbuffer::noalloc, printbuffer::offset, parse_object, print_object, reset.
Referenced by print_object_should_print_empty_objects, print_object_should_print_objects_with_multiple_elements, print_object_should_print_objects_with_one_element.
static void print_object_should_print_empty_objects(void)
References assert_print_object.
Referenced by main.
static void print_object_should_print_objects_with_one_element(void)
References assert_print_object.
Referenced by main.
static void print_object_should_print_objects_with_multiple_elements(void)
References assert_print_object.
Referenced by main.
int main(void)
References print_object_should_print_empty_objects, print_object_should_print_objects_with_multiple_elements, print_object_should_print_objects_with_one_element.