print_string.c
static void assert_print_string(const char *expected, const char *input)
References printbuffer::buffer, global_hooks, printbuffer::hooks, printbuffer::length, printbuffer::noalloc, printbuffer::offset, print_string_ptr.
Referenced by print_string_should_print_ascii, print_string_should_print_empty_strings, print_string_should_print_utf8.
static void print_string_should_print_empty_strings(void)
References assert_print_string.
Referenced by main.
static void print_string_should_print_ascii(void)
References assert_print_string.
Referenced by main.
static void print_string_should_print_utf8(void)
References assert_print_string.
Referenced by main.
int main(void)
References print_string_should_print_ascii, print_string_should_print_empty_strings, print_string_should_print_utf8.