print_array.c
static void assert_print_array(const char *const expected, const char *const input)
References printbuffer::buffer, parse_buffer::content, printbuffer::format, global_hooks, parse_buffer::hooks, printbuffer::hooks, parse_buffer::length, printbuffer::length, printbuffer::noalloc, printbuffer::offset, parse_array, print_array, reset.
Referenced by print_array_should_print_arrays_with_multiple_elements, print_array_should_print_arrays_with_one_element, print_array_should_print_empty_arrays.
static void print_array_should_print_empty_arrays(void)
References assert_print_array.
Referenced by main.
static void print_array_should_print_arrays_with_one_element(void)
References assert_print_array.
Referenced by main.
static void print_array_should_print_arrays_with_multiple_elements(void)
References assert_print_array.
Referenced by main.
int main(void)
References print_array_should_print_arrays_with_multiple_elements, print_array_should_print_arrays_with_one_element, print_array_should_print_empty_arrays.