readme_examples.c
const char* json
Referenced by assert_not_array, assert_not_object, assert_parse_array, assert_parse_object, cJSON_Minify, create_monitor_should_create_a_monitor, create_monitor_with_helpers_should_create_a_monitor, json_pointer_tests, LLVMFuzzerTestOneInput, main, parse_test_file, parse_with_opts_should_handle_incomplete_json, parse_with_opts_should_return_parse_end, supports_full_hd_should_check_for_full_hd_support.
static char* create_monitor(void)
References cJSON_AddItemToArray, cJSON_AddItemToObject, cJSON_CreateArray, cJSON_CreateNumber, cJSON_CreateObject, cJSON_CreateString, cJSON_Delete, cJSON_Print.
Referenced by create_monitor_should_create_a_monitor.
static char* create_monitor_with_helpers(void)
References cJSON_AddArrayToObject, cJSON_AddItemToArray, cJSON_AddNumberToObject, cJSON_AddStringToObject, cJSON_CreateObject, cJSON_Delete, cJSON_Print.
Referenced by create_monitor_with_helpers_should_create_a_monitor.
static int supports_full_hd(const char *const monitor)
References cJSON_Delete, cJSON_GetErrorPtr, cJSON_GetObjectItemCaseSensitive, cJSON_IsNumber, cJSON_IsString, cJSON_Parse, compare_double, cJSON::valuedouble, cJSON::valuestring.
Referenced by supports_full_hd_should_check_for_full_hd_support.
static void create_monitor_should_create_a_monitor(void)
References create_monitor, json.
Referenced by main.
static void create_monitor_with_helpers_should_create_a_monitor(void)
References create_monitor_with_helpers, json.
Referenced by main.
static void supports_full_hd_should_check_for_full_hd_support(void)
References json, supports_full_hd.
Referenced by main.
int main(void)
References create_monitor_should_create_a_monitor, create_monitor_with_helpers_should_create_a_monitor, supports_full_hd_should_check_for_full_hd_support.