testsample_cmd.c
RUN_TEST
void setUp(void)
void tearDown(void)
void test_TheFirstThingToTest(void)
Referenced by main.
void test_TheSecondThingToTest(void)
Referenced by main.
void test_TheThirdThingToTest(void)
Referenced by main.
void test_TheFourthThingToTest(void)
Referenced by main.
void resetTest(void)
References setUp, tearDown.
int main(void)
References test_TheFirstThingToTest, test_TheFourthThingToTest, test_TheSecondThingToTest, test_TheThirdThingToTest, UnityBegin, UnityEnd.