testsample_mock_cmd.c
RUN_TEST
void setUp(void)
void tearDown(void)
void test_TheFirstThingToTest(void)
void test_TheSecondThingToTest(void)
static void CMock_Init(void)
Referenced by resetTest.
static void CMock_Verify(void)
Referenced by resetTest.
static void CMock_Destroy(void)
Referenced by resetTest.
void resetTest(void)
References CMock_Destroy, CMock_Init, CMock_Verify, setUp, tearDown.
int main(void)
References CMock_Guts_MemFreeFinal, test_TheFirstThingToTest, test_TheSecondThingToTest, UnityBegin, UnityEnd.