unity_fixture_internals.h
UNITY_MAX_POINTERS
typedef void unityfunction(void)(void)
struct UNITY_FIXTURE_T UnityFixture
Referenced by announceTestRun, groupSelected, TEST, TEST_SETUP, TEST_TEAR_DOWN, testSelected, UnityConcludeFixtureTest, UnityGetCommandLineOptions, UnityIgnoreTest, UnityMain, UnityTestRunner.
void UnityTestRunner(unityfunction *setup, unityfunction *body, unityfunction *teardown, const char *printableName, const char *group, const char *name, const char *file, unsigned int line)
References UNITY_STORAGE_T::CurrentTestFailed, UNITY_STORAGE_T::CurrentTestLineNumber, UNITY_STORAGE_T::CurrentTestName, group, groupSelected, name, UNITY_STORAGE_T::NumberOfTests, TEST_PROTECT, UNITY_STORAGE_T::TestFile, testSelected, Unity, UNITY_OUTPUT_CHAR, UnityConcludeFixtureTest, UnityFixture, UnityMalloc_EndTest, UnityMalloc_StartTest, UnityPointer_Init, UnityPointer_UndoAllSets, UnityPrint, UNITY_FIXTURE_T::Verbose.
void UnityIgnoreTest(const char *printableName, const char *group, const char *name)
References group, groupSelected, name, UNITY_STORAGE_T::NumberOfTests, UNITY_STORAGE_T::TestIgnores, testSelected, Unity, UNITY_OUTPUT_CHAR, UNITY_PRINT_EOL, UnityFixture, UnityPrint, UNITY_FIXTURE_T::Verbose.
Referenced by TEST.
void UnityMalloc_StartTest(void)
References malloc_count, MALLOC_DONT_FAIL, malloc_fail_countdown.
Referenced by UnityTestRunner.
void UnityMalloc_EndTest(void)
References UNITY_STORAGE_T::CurrentTestLineNumber, malloc_count, MALLOC_DONT_FAIL, malloc_fail_countdown, Unity, UNITY_TEST_FAIL.
Referenced by UnityTestRunner.
int UnityGetCommandLineOptions(int argc, const char *argv[])
References UNITY_FIXTURE_T::GroupFilter, UNITY_FIXTURE_T::NameFilter, UNITY_FIXTURE_T::RepeatCount, UnityFixture, UNITY_FIXTURE_T::Verbose.
Referenced by TEST, UnityMain.
void UnityConcludeFixtureTest(void)
References UNITY_STORAGE_T::CurrentTestFailed, UNITY_STORAGE_T::CurrentTestIgnored, UNITY_STORAGE_T::TestFailures, UNITY_STORAGE_T::TestIgnores, Unity, UNITY_PRINT_EOL, UnityFixture, UnityPrint, UNITY_FIXTURE_T::Verbose.
Referenced by TEST, UnityTestRunner.
void UnityPointer_Set(void **ptr, void *newValue, UNITY_LINE_TYPE line)
References PointerPair::old_value, PointerPair::pointer, pointer_index, pointer_store, UNITY_MAX_POINTERS, UNITY_TEST_FAIL.
void UnityPointer_UndoAllSets(void)
References PointerPair::old_value, PointerPair::pointer, pointer_index, pointer_store.
Referenced by TEST, UnityTestRunner.
void UnityPointer_Init(void)
References pointer_index.
Referenced by TEST, UnityTestRunner.