unity_output_Spy.h
void UnityOutputCharSpy_Create(int s)
References buffer, count, malloc, size, spy_enable, TEST_ASSERT_NOT_NULL_MESSAGE.
Referenced by TEST_SETUP.
void UnityOutputCharSpy_Destroy(void)
References buffer, free, size, unity_free.
Referenced by TEST_TEAR_DOWN.
void UnityOutputCharSpy_OutputChar(int c)
References buffer, count, size, spy_enable.
const char* UnityOutputCharSpy_Get(void)
References buffer.
Referenced by TEST.
void UnityOutputCharSpy_Enable(int enable)
References spy_enable.
Referenced by TEST.