unity_fixture.c
MALLOC_DONT_FAIL
typedef struct GuardBytes Guard
struct UNITY_FIXTURE_T UnityFixture
Referenced by announceTestRun, groupSelected, TEST, TEST_SETUP, TEST_TEAR_DOWN, testSelected, UnityConcludeFixtureTest, UnityGetCommandLineOptions, UnityIgnoreTest, UnityMain, UnityTestRunner.
int malloc_count
Referenced by release_memory, unity_malloc, UnityMalloc_EndTest, UnityMalloc_StartTest.
int malloc_fail_countdown
Referenced by unity_malloc, UnityMalloc_EndTest, UnityMalloc_MakeMallocFailAfterCount, UnityMalloc_StartTest.
const char end[][]
Referenced by cjson_replace_item_via_pointer_should_replace_items, create_monitor, create_monitor_with_helpers, isOverrun, supports_full_hd, unity_malloc.
struct PointerPair pointer_store[5][5]
Referenced by UnityPointer_Set, UnityPointer_UndoAllSets.
int pointer_index
Referenced by UnityPointer_Init, UnityPointer_Set, UnityPointer_UndoAllSets.
void setUp(void)
void tearDown(void)
static void announceTestRun(unsigned int runNumber)
References UNITY_FIXTURE_T::RepeatCount, UnityFixture, UnityPrint, UnityPrintNumberUnsigned.
Referenced by UnityMain.
int UnityMain(int argc, const char *argv[], void(*runAllTests)(void))
References announceTestRun, UNITY_FIXTURE_T::RepeatCount, UNITY_STORAGE_T::TestFailures, Unity, UnityBegin, UnityEnd, UnityFixture, UnityGetCommandLineOptions, UNITY_FIXTURE_T::Verbose.
Referenced by main, TEST.
static int selected(const char *filter, const char *name)
Referenced by groupSelected, testSelected.
static int testSelected(const char *test)
References UNITY_FIXTURE_T::NameFilter, selected, UnityFixture.
Referenced by UnityIgnoreTest, UnityTestRunner.
static int groupSelected(const char *group)
References UNITY_FIXTURE_T::GroupFilter, selected, UnityFixture.
Referenced by UnityIgnoreTest, UnityTestRunner.
void UnityTestRunner(unityfunction *setup, unityfunction *testBody, unityfunction *teardown, const char *printableName, const char *group, const char *name, const char *file, unsigned int line)
References UNITY_STORAGE_T::CurrentTestFailed, UNITY_STORAGE_T::CurrentTestLineNumber, UNITY_STORAGE_T::CurrentTestName, groupSelected, UNITY_STORAGE_T::NumberOfTests, UNITY_STORAGE_T::TestFile, testSelected, Unity, UnityConcludeFixtureTest, UnityFixture, UnityMalloc_EndTest, UnityMalloc_StartTest, UnityPointer_Init, UnityPointer_UndoAllSets, UnityPrint, UNITY_FIXTURE_T::Verbose.
void UnityIgnoreTest(const char *printableName, const char *group, const char *name)
References groupSelected, UNITY_STORAGE_T::NumberOfTests, UNITY_STORAGE_T::TestIgnores, testSelected, Unity, UnityFixture, UnityPrint, UNITY_FIXTURE_T::Verbose.
Referenced by TEST.
void UnityMalloc_StartTest(void)
References malloc_count, malloc_fail_countdown.
Referenced by UnityTestRunner.
void UnityMalloc_EndTest(void)
References UNITY_STORAGE_T::CurrentTestLineNumber, malloc_count, malloc_fail_countdown, Unity.
Referenced by UnityTestRunner.
void UnityMalloc_MakeMallocFailAfterCount(int countdown)
References malloc_fail_countdown.
Referenced by TEST.
void* unity_malloc(size_t size)
References end, GuardBytes::guard_space, malloc_count, malloc_fail_countdown, GuardBytes::size.
Referenced by TEST, unity_calloc.
static int isOverrun(void *mem)
References end, GuardBytes::guard_space, GuardBytes::size.
Referenced by unity_free.
static void release_memory(void *mem)
References malloc_count.
Referenced by unity_free.
void unity_free(void *mem)
References UNITY_STORAGE_T::CurrentTestLineNumber, isOverrun, release_memory, Unity.
Referenced by TEST, UnityOutputCharSpy_Destroy.
void* unity_calloc(size_t num, size_t size)
References unity_malloc.
Referenced by TEST.
void* unity_realloc(void *oldMem, size_t size)
Referenced by TEST.
void UnityPointer_Init(void)
References pointer_index.
Referenced by TEST, UnityTestRunner.
void UnityPointer_Set(void **pointer, void *newValue, UNITY_LINE_TYPE line)
References PointerPair::old_value, PointerPair::pointer, pointer_index, pointer_store.
void UnityPointer_UndoAllSets(void)
References PointerPair::old_value, PointerPair::pointer, pointer_index, pointer_store.
Referenced by TEST, UnityTestRunner.
int UnityGetCommandLineOptions(int argc, const char *argv[])
References UNITY_FIXTURE_T::GroupFilter, UNITY_FIXTURE_T::NameFilter, UNITY_FIXTURE_T::RepeatCount, UnityFixture, UNITY_FIXTURE_T::Verbose.
Referenced by TEST, UnityMain.
void UnityConcludeFixtureTest(void)
References UNITY_STORAGE_T::CurrentTestFailed, UNITY_STORAGE_T::CurrentTestIgnored, UNITY_STORAGE_T::TestFailures, UNITY_STORAGE_T::TestIgnores, Unity, UnityFixture, UnityPrint, UNITY_FIXTURE_T::Verbose.
Referenced by TEST, UnityTestRunner.