unity_fixture_malloc_overrides.h
UNITY_FIXTURE_MALLOC
UNITY_FIXTURE_FREE
malloc
calloc
realloc
free
void* unity_malloc(size_t size)
References end, GuardBytes::guard_space, malloc_count, MALLOC_DONT_FAIL, malloc_fail_countdown, GuardBytes::size, size, UNITY_FIXTURE_MALLOC.
Referenced by TEST, unity_calloc.
void* unity_calloc(size_t num, size_t size)
References size, unity_malloc.
Referenced by TEST.
void* unity_realloc(void *oldMem, size_t size)
Referenced by TEST.
void unity_free(void *mem)
References UNITY_STORAGE_T::CurrentTestLineNumber, isOverrun, release_memory, Unity, UNITY_TEST_FAIL.
Referenced by TEST, UnityOutputCharSpy_Destroy.