unity_setup.c
void setUp(void)
References Counter.
Referenced by resetTest, UnityDefaultTestRun.
void tearDown(void)
Referenced by resetTest, UnityDefaultTestRun.