unity_internals.h
UNITY_INT_WIDTH
UNITY_LONG_WIDTH
UNITY_POINTER_WIDTH
UNITY_PTR_TO_INT
UNITY_DISPLAY_STYLE_POINTER
UNITY_PTR_ATTRIBUTE
UNITY_INTERNAL_PTR
UNITY_FLOAT_PRECISION
UNITY_FLOAT_TYPE
isinf
isnan
UNITY_DOUBLE_PRECISION
UNITY_DOUBLE_TYPE
UNITY_OUTPUT_CHAR
UNITY_OUTPUT_FLUSH
UNITY_FLUSH_CALL
UNITY_PRINT_EOL
UNITY_OUTPUT_START
UNITY_OUTPUT_COMPLETE
UNITY_LINE_TYPE
UNITY_COUNTER_TYPE
UNITY_DISPLAY_RANGE_INT
UNITY_DISPLAY_RANGE_UINT
UNITY_DISPLAY_RANGE_HEX
UNITY_CLR_DETAILS
UNITY_SET_DETAIL
UNITY_SET_DETAILS
UNITY_DETAIL1_NAME
UNITY_DETAIL2_NAME
TEST_PROTECT
TEST_ABORT
RUN_TEST
TEST_LINE_NUM
TEST_IS_IGNORED
UNITY_NEW_TEST
UNITY_BEGIN
UNITY_END
UNITY_TEST_FAIL
UNITY_TEST_IGNORE
UNITY_TEST_ASSERT
UNITY_TEST_ASSERT_NULL
UNITY_TEST_ASSERT_NOT_NULL
UNITY_TEST_ASSERT_EQUAL_INT
UNITY_TEST_ASSERT_EQUAL_INT8
UNITY_TEST_ASSERT_EQUAL_INT16
UNITY_TEST_ASSERT_EQUAL_INT32
UNITY_TEST_ASSERT_EQUAL_UINT
UNITY_TEST_ASSERT_EQUAL_UINT8
UNITY_TEST_ASSERT_EQUAL_UINT16
UNITY_TEST_ASSERT_EQUAL_UINT32
UNITY_TEST_ASSERT_EQUAL_HEX8
UNITY_TEST_ASSERT_EQUAL_HEX16
UNITY_TEST_ASSERT_EQUAL_HEX32
UNITY_TEST_ASSERT_BITS
UNITY_TEST_ASSERT_GREATER_THAN_INT
UNITY_TEST_ASSERT_GREATER_THAN_INT8
UNITY_TEST_ASSERT_GREATER_THAN_INT16
UNITY_TEST_ASSERT_GREATER_THAN_INT32
UNITY_TEST_ASSERT_GREATER_THAN_UINT
UNITY_TEST_ASSERT_GREATER_THAN_UINT8
UNITY_TEST_ASSERT_GREATER_THAN_UINT16
UNITY_TEST_ASSERT_GREATER_THAN_UINT32
UNITY_TEST_ASSERT_GREATER_THAN_HEX8
UNITY_TEST_ASSERT_GREATER_THAN_HEX16
UNITY_TEST_ASSERT_GREATER_THAN_HEX32
UNITY_TEST_ASSERT_SMALLER_THAN_INT
UNITY_TEST_ASSERT_SMALLER_THAN_INT8
UNITY_TEST_ASSERT_SMALLER_THAN_INT16
UNITY_TEST_ASSERT_SMALLER_THAN_INT32
UNITY_TEST_ASSERT_SMALLER_THAN_UINT
UNITY_TEST_ASSERT_SMALLER_THAN_UINT8
UNITY_TEST_ASSERT_SMALLER_THAN_UINT16
UNITY_TEST_ASSERT_SMALLER_THAN_UINT32
UNITY_TEST_ASSERT_SMALLER_THAN_HEX8
UNITY_TEST_ASSERT_SMALLER_THAN_HEX16
UNITY_TEST_ASSERT_SMALLER_THAN_HEX32
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_INT
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_INT8
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_INT16
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_INT32
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_UINT
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_UINT8
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_UINT16
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_UINT32
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_HEX8
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_HEX16
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_HEX32
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_INT
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_INT8
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_INT16
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_INT32
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_UINT
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_UINT8
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_UINT16
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_UINT32
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_HEX8
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_HEX16
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_HEX32
UNITY_TEST_ASSERT_INT_WITHIN
UNITY_TEST_ASSERT_INT8_WITHIN
UNITY_TEST_ASSERT_INT16_WITHIN
UNITY_TEST_ASSERT_INT32_WITHIN
UNITY_TEST_ASSERT_UINT_WITHIN
UNITY_TEST_ASSERT_UINT8_WITHIN
UNITY_TEST_ASSERT_UINT16_WITHIN
UNITY_TEST_ASSERT_UINT32_WITHIN
UNITY_TEST_ASSERT_HEX8_WITHIN
UNITY_TEST_ASSERT_HEX16_WITHIN
UNITY_TEST_ASSERT_HEX32_WITHIN
UNITY_TEST_ASSERT_EQUAL_PTR
UNITY_TEST_ASSERT_EQUAL_STRING
UNITY_TEST_ASSERT_EQUAL_STRING_LEN
UNITY_TEST_ASSERT_EQUAL_MEMORY
UNITY_TEST_ASSERT_EQUAL_INT_ARRAY
UNITY_TEST_ASSERT_EQUAL_INT8_ARRAY
UNITY_TEST_ASSERT_EQUAL_INT16_ARRAY
UNITY_TEST_ASSERT_EQUAL_INT32_ARRAY
UNITY_TEST_ASSERT_EQUAL_UINT_ARRAY
UNITY_TEST_ASSERT_EQUAL_UINT8_ARRAY
UNITY_TEST_ASSERT_EQUAL_UINT16_ARRAY
UNITY_TEST_ASSERT_EQUAL_UINT32_ARRAY
UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY
UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY
UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY
UNITY_TEST_ASSERT_EQUAL_PTR_ARRAY
UNITY_TEST_ASSERT_EQUAL_STRING_ARRAY
UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY
UNITY_TEST_ASSERT_EACH_EQUAL_INT
UNITY_TEST_ASSERT_EACH_EQUAL_INT8
UNITY_TEST_ASSERT_EACH_EQUAL_INT16
UNITY_TEST_ASSERT_EACH_EQUAL_INT32
UNITY_TEST_ASSERT_EACH_EQUAL_UINT
UNITY_TEST_ASSERT_EACH_EQUAL_UINT8
UNITY_TEST_ASSERT_EACH_EQUAL_UINT16
UNITY_TEST_ASSERT_EACH_EQUAL_UINT32
UNITY_TEST_ASSERT_EACH_EQUAL_HEX8
UNITY_TEST_ASSERT_EACH_EQUAL_HEX16
UNITY_TEST_ASSERT_EACH_EQUAL_HEX32
UNITY_TEST_ASSERT_EACH_EQUAL_PTR
UNITY_TEST_ASSERT_EACH_EQUAL_STRING
UNITY_TEST_ASSERT_EACH_EQUAL_MEMORY
UNITY_TEST_ASSERT_EQUAL_INT64
UNITY_TEST_ASSERT_EQUAL_UINT64
UNITY_TEST_ASSERT_EQUAL_HEX64
UNITY_TEST_ASSERT_EQUAL_INT64_ARRAY
UNITY_TEST_ASSERT_EQUAL_UINT64_ARRAY
UNITY_TEST_ASSERT_EQUAL_HEX64_ARRAY
UNITY_TEST_ASSERT_INT64_WITHIN
UNITY_TEST_ASSERT_UINT64_WITHIN
UNITY_TEST_ASSERT_HEX64_WITHIN
UNITY_TEST_ASSERT_GREATER_THAN_INT64
UNITY_TEST_ASSERT_GREATER_THAN_UINT64
UNITY_TEST_ASSERT_GREATER_THAN_HEX64
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_INT64
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_UINT64
UNITY_TEST_ASSERT_GREATER_OR_EQUAL_HEX64
UNITY_TEST_ASSERT_SMALLER_THAN_INT64
UNITY_TEST_ASSERT_SMALLER_THAN_UINT64
UNITY_TEST_ASSERT_SMALLER_THAN_HEX64
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_INT64
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_UINT64
UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_HEX64
UNITY_TEST_ASSERT_FLOAT_WITHIN
UNITY_TEST_ASSERT_EQUAL_FLOAT
UNITY_TEST_ASSERT_EQUAL_FLOAT_ARRAY
UNITY_TEST_ASSERT_EACH_EQUAL_FLOAT
UNITY_TEST_ASSERT_FLOAT_IS_INF
UNITY_TEST_ASSERT_FLOAT_IS_NEG_INF
UNITY_TEST_ASSERT_FLOAT_IS_NAN
UNITY_TEST_ASSERT_FLOAT_IS_DETERMINATE
UNITY_TEST_ASSERT_FLOAT_IS_NOT_INF
UNITY_TEST_ASSERT_FLOAT_IS_NOT_NEG_INF
UNITY_TEST_ASSERT_FLOAT_IS_NOT_NAN
UNITY_TEST_ASSERT_FLOAT_IS_NOT_DETERMINATE
UNITY_TEST_ASSERT_DOUBLE_WITHIN
UNITY_TEST_ASSERT_EQUAL_DOUBLE
UNITY_TEST_ASSERT_EQUAL_DOUBLE_ARRAY
UNITY_TEST_ASSERT_EACH_EQUAL_DOUBLE
UNITY_TEST_ASSERT_DOUBLE_IS_INF
UNITY_TEST_ASSERT_DOUBLE_IS_NEG_INF
UNITY_TEST_ASSERT_DOUBLE_IS_NAN
UNITY_TEST_ASSERT_DOUBLE_IS_DETERMINATE
UNITY_TEST_ASSERT_DOUBLE_IS_NOT_INF
UNITY_TEST_ASSERT_DOUBLE_IS_NOT_NEG_INF
UNITY_TEST_ASSERT_DOUBLE_IS_NOT_NAN
UNITY_TEST_ASSERT_DOUBLE_IS_NOT_DETERMINATE
UNITY_DISPLAY_STYLE_T
UNITY_COMPARISON_T
UNITY_FLOAT_TRAIT
UNITY_FLAGS_T
typedef unsigned char UNITY_UINT8
typedef unsigned short UNITY_UINT16
typedef unsigned int UNITY_UINT32
typedef signed char UNITY_INT8
typedef signed short UNITY_INT16
typedef signed int UNITY_INT32
typedef UNITY_UINT32 UNITY_UINT
typedef UNITY_INT32 UNITY_INT
typedef float UNITY_FLOAT
typedef double UNITY_DOUBLE
typedef void(* UnityTestFunction) (void))(void)
typedef enum UNITY_FLOAT_TRAIT UNITY_FLOAT_TRAIT_T
struct UNITY_STORAGE_T Unity
Referenced by tearDown, TEST, test_ShouldCallMockInitAndVerifyFunctionsForEachTest, unity_free, UnityAddMsgIfSpecified, UnityAssertEqualString, UnityAssertEqualStringArray, UnityAssertEqualStringLen, UnityAssertNumbersWithin, UnityBegin, UnityConcludeFixtureTest, UnityConcludeTest, UnityDefaultTestRun, UnityEnd, UnityFail, UnityIgnore, UnityIgnoreTest, UnityMain, UnityMalloc_EndTest, UnityTestResultsBegin, UnityTestResultsFailBegin, UnityTestRunner.
const char UnityStrErrFloat[][]
const char UnityStrErrDouble[][]
const char UnityStrErr64[][]
void UnityBegin(const char *filename)
References UNITY_STORAGE_T::CurrentTestFailed, UNITY_STORAGE_T::CurrentTestIgnored, UNITY_STORAGE_T::CurrentTestLineNumber, UNITY_STORAGE_T::CurrentTestName, UNITY_STORAGE_T::NumberOfTests, UNITY_STORAGE_T::TestFailures, UNITY_STORAGE_T::TestFile, UNITY_STORAGE_T::TestIgnores, Unity, UNITY_CLR_DETAILS, UNITY_OUTPUT_START.
Referenced by main, UnityMain.
int UnityEnd(void)
References UNITY_STORAGE_T::NumberOfTests, UNITY_STORAGE_T::TestFailures, UNITY_STORAGE_T::TestIgnores, Unity, UNITY_FLUSH_CALL, UNITY_OUTPUT_CHAR, UNITY_OUTPUT_COMPLETE, UNITY_PRINT_EOL, UnityPrint, UnityPrintNumber, UnityStrBreaker, UnityStrFail, UnityStrOk, UnityStrResultsFailures, UnityStrResultsIgnored, UnityStrResultsTests.
Referenced by main, UnityMain.
void UnityConcludeTest(void)
References UNITY_STORAGE_T::CurrentTestFailed, UNITY_STORAGE_T::CurrentTestIgnored, UNITY_STORAGE_T::CurrentTestLineNumber, UNITY_STORAGE_T::TestFailures, UNITY_STORAGE_T::TestFile, UNITY_STORAGE_T::TestIgnores, Unity, UNITY_FLUSH_CALL, UNITY_PRINT_EOL, UnityPrint, UnityStrPass, UnityTestResultsBegin.
Referenced by UnityDefaultTestRun.
void UnityDefaultTestRun(UnityTestFunction Func, const char *FuncName, const int FuncLineNum)
References UNITY_STORAGE_T::CurrentTestLineNumber, UNITY_STORAGE_T::CurrentTestName, UNITY_STORAGE_T::NumberOfTests, setUp, tearDown, TEST_PROTECT, Unity, UNITY_CLR_DETAILS, UNITY_LINE_TYPE, UnityConcludeTest.
void UnityPrint(const char *string)
References UNITY_OUTPUT_CHAR, UnityPrintNumberHex.
Referenced by announceTestRun, tearDown, UnityAddMsgIfSpecified, UnityAssertBits, UnityAssertDoubleSpecial, UnityAssertEqualDoubleArray, UnityAssertEqualFloatArray, UnityAssertEqualIntArray, UnityAssertEqualMemory, UnityAssertEqualNumber, UnityAssertEqualStringArray, UnityAssertFloatSpecial, UnityAssertGreaterOrLessOrEqualNumber, UnityAssertNumbersWithin, UnityConcludeFixtureTest, UnityConcludeTest, UnityEnd, UnityFail, UnityIgnore, UnityIgnoreTest, UnityIsOneArrayNull, UnityPrintExpectedAndActualStrings, UnityPrintExpectedAndActualStringsLen, UnityPrintFloat, UnityTestResultsBegin, UnityTestResultsFailBegin, UnityTestRunner.
void UnityPrintLen(const char *string, const UNITY_UINT32 length)
References UNITY_OUTPUT_CHAR, UnityPrintNumberHex.
Referenced by UnityPrintExpectedAndActualStringsLen.
void UnityPrintMask(const UNITY_UINT mask, const UNITY_UINT number)
References UNITY_INT_WIDTH, UNITY_OUTPUT_CHAR.
Referenced by UnityAssertBits.
void UnityPrintNumberByStyle(const UNITY_INT number, const UNITY_DISPLAY_STYLE_T style)
References UNITY_DISPLAY_RANGE_INT, UNITY_DISPLAY_RANGE_UINT, UNITY_OUTPUT_CHAR, UnityPrintNumber, UnityPrintNumberHex, UnityPrintNumberUnsigned.
Referenced by UnityAssertEqualIntArray, UnityAssertEqualMemory, UnityAssertEqualNumber, UnityAssertGreaterOrLessOrEqualNumber, UnityAssertNumbersWithin.
void UnityPrintNumber(const UNITY_INT number)
References UNITY_OUTPUT_CHAR, UnityPrintNumberUnsigned.
Referenced by UnityEnd, UnityPrintNumberByStyle, UnityTestResultsBegin.
void UnityPrintNumberUnsigned(const UNITY_UINT number)
References UNITY_OUTPUT_CHAR.
Referenced by announceTestRun, UnityAssertEqualDoubleArray, UnityAssertEqualFloatArray, UnityAssertEqualIntArray, UnityAssertEqualMemory, UnityAssertEqualStringArray, UnityPrintNumber, UnityPrintNumberByStyle.
void UnityPrintNumberHex(const UNITY_UINT number, const char nibbles)
References UNITY_OUTPUT_CHAR.
Referenced by UnityPrint, UnityPrintLen, UnityPrintNumberByStyle.
void UnityPrintFloat(const UNITY_DOUBLE input_number)
References isinf, isnan, UNITY_OUTPUT_CHAR, UnityPrint.
Referenced by UnityAssertDoubleSpecial, UnityAssertFloatSpecial.
void UnityAssertEqualNumber(const UNITY_INT expected, const UNITY_INT actual, const char *msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style)
References RETURN_IF_FAIL_OR_IGNORE, UNITY_FAIL_AND_BAIL, UnityAddMsgIfSpecified, UnityPrint, UnityPrintNumberByStyle, UnityStrExpected, UnityStrWas, UnityTestResultsFailBegin.
void UnityAssertGreaterOrLessOrEqualNumber(const UNITY_INT threshold, const UNITY_INT actual, const UNITY_COMPARISON_T compare, const char *msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style)
References RETURN_IF_FAIL_OR_IGNORE, UNITY_DISPLAY_RANGE_INT, UNITY_EQUAL_TO, UNITY_FAIL_AND_BAIL, UNITY_GREATER_THAN, UNITY_SMALLER_THAN, UnityAddMsgIfSpecified, UnityPrint, UnityPrintNumberByStyle, UnityStrExpected, UnityStrGt, UnityStrLt, UnityStrOrEqual, UnityTestResultsFailBegin.
void UnityAssertEqualIntArray(const void *expected, const void *actual, const UNITY_UINT32 num_elements, const char *msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style, const UNITY_FLAGS_T flags)
References RETURN_IF_FAIL_OR_IGNORE, UNITY_ARRAY_TO_ARRAY, UNITY_DISPLAY_RANGE_UINT, UNITY_FAIL_AND_BAIL, UNITY_INTERNAL_PTR, UNITY_PTR_ATTRIBUTE, UnityAddMsgIfSpecified, UnityIsOneArrayNull, UnityPrint, UnityPrintNumberByStyle, UnityPrintNumberUnsigned, UnityPrintPointlessAndBail, UnityStrElement, UnityStrExpected, UnityStrWas, UnityTestResultsFailBegin.
void UnityAssertBits(const UNITY_INT mask, const UNITY_INT expected, const UNITY_INT actual, const char *msg, const UNITY_UINT lineNumber)
References RETURN_IF_FAIL_OR_IGNORE, UNITY_FAIL_AND_BAIL, UnityAddMsgIfSpecified, UnityPrint, UnityPrintMask, UnityStrExpected, UnityStrWas, UnityTestResultsFailBegin.
void UnityAssertEqualString(const char *expected, const char *actual, const char *msg, const UNITY_UINT lineNumber)
References UNITY_STORAGE_T::CurrentTestFailed, RETURN_IF_FAIL_OR_IGNORE, Unity, UNITY_FAIL_AND_BAIL, UnityAddMsgIfSpecified, UnityPrintExpectedAndActualStrings, UnityTestResultsFailBegin.
void UnityAssertEqualStringLen(const char *expected, const char *actual, const UNITY_UINT32 length, const char *msg, const UNITY_UINT lineNumber)
References UNITY_STORAGE_T::CurrentTestFailed, RETURN_IF_FAIL_OR_IGNORE, Unity, UNITY_FAIL_AND_BAIL, UnityAddMsgIfSpecified, UnityPrintExpectedAndActualStringsLen, UnityTestResultsFailBegin.
void UnityAssertEqualStringArray(const void *expected, const char **actual, const UNITY_UINT32 num_elements, const char *msg, const UNITY_UINT lineNumber, const UNITY_FLAGS_T flags)
References UNITY_STORAGE_T::CurrentTestFailed, RETURN_IF_FAIL_OR_IGNORE, Unity, UNITY_ARRAY_TO_ARRAY, UNITY_FAIL_AND_BAIL, UNITY_INTERNAL_PTR, UnityAddMsgIfSpecified, UnityIsOneArrayNull, UnityPrint, UnityPrintExpectedAndActualStrings, UnityPrintNumberUnsigned, UnityPrintPointlessAndBail, UnityStrElement, UnityTestResultsFailBegin.
void UnityAssertEqualMemory(const void *expected, const void *actual, const UNITY_UINT32 length, const UNITY_UINT32 num_elements, const char *msg, const UNITY_UINT lineNumber, const UNITY_FLAGS_T flags)
References RETURN_IF_FAIL_OR_IGNORE, UNITY_ARRAY_TO_VAL, UNITY_DISPLAY_STYLE_HEX8, UNITY_FAIL_AND_BAIL, UNITY_PTR_ATTRIBUTE, UnityAddMsgIfSpecified, UnityIsOneArrayNull, UnityPrint, UnityPrintNumberByStyle, UnityPrintNumberUnsigned, UnityPrintPointlessAndBail, UnityStrByte, UnityStrElement, UnityStrExpected, UnityStrMemory, UnityStrWas, UnityTestResultsFailBegin.
void UnityAssertNumbersWithin(const UNITY_UINT delta, const UNITY_INT expected, const UNITY_INT actual, const char *msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style)
References UNITY_STORAGE_T::CurrentTestFailed, RETURN_IF_FAIL_OR_IGNORE, Unity, UNITY_DISPLAY_RANGE_INT, UNITY_FAIL_AND_BAIL, UnityAddMsgIfSpecified, UnityPrint, UnityPrintNumberByStyle, UnityStrDelta, UnityStrExpected, UnityStrWas, UnityTestResultsFailBegin.
void UnityFail(const char *message, const UNITY_UINT line)
References UNITY_STORAGE_T::CurrentDetail1, UNITY_STORAGE_T::CurrentDetail2, RETURN_IF_FAIL_OR_IGNORE, UNITY_STORAGE_T::TestFile, Unity, UNITY_FAIL_AND_BAIL, UNITY_OUTPUT_CHAR, UnityPrint, UnityStrDetail1Name, UnityStrDetail2Name, UnityStrFail, UnityStrSpacer, UnityTestResultsBegin.
void UnityIgnore(const char *message, const UNITY_UINT line)
References RETURN_IF_FAIL_OR_IGNORE, UNITY_STORAGE_T::TestFile, Unity, UNITY_IGNORE_AND_BAIL, UNITY_OUTPUT_CHAR, UnityPrint, UnityStrIgnore, UnityTestResultsBegin.
void UnityAssertFloatsWithin(const UNITY_FLOAT delta, const UNITY_FLOAT expected, const UNITY_FLOAT actual, const char *msg, const UNITY_UINT lineNumber)
References RETURN_IF_FAIL_OR_IGNORE, UNITY_FAIL_AND_BAIL, UNITY_PRINT_EXPECTED_AND_ACTUAL_FLOAT, UnityAddMsgIfSpecified, UnityFloatsWithin, UnityTestResultsFailBegin.
void UnityAssertEqualFloatArray(const UNITY_FLOAT *expected, const UNITY_FLOAT *actual, const UNITY_UINT32 num_elements, const char *msg, const UNITY_UINT lineNumber, const UNITY_FLAGS_T flags)
References RETURN_IF_FAIL_OR_IGNORE, UNITY_ARRAY_TO_ARRAY, UNITY_FAIL_AND_BAIL, UNITY_FLOAT_PRECISION, UNITY_INTERNAL_PTR, UNITY_PRINT_EXPECTED_AND_ACTUAL_FLOAT, UNITY_PTR_ATTRIBUTE, UnityAddMsgIfSpecified, UnityFloatsWithin, UnityIsOneArrayNull, UnityPrint, UnityPrintNumberUnsigned, UnityPrintPointlessAndBail, UnityStrElement, UnityTestResultsFailBegin.
void UnityAssertFloatSpecial(const UNITY_FLOAT actual, const char *msg, const UNITY_UINT lineNumber, const UNITY_FLOAT_TRAIT_T style)
References isinf, isnan, RETURN_IF_FAIL_OR_IGNORE, UNITY_FAIL_AND_BAIL, UNITY_FLOAT_IS_DET, UNITY_FLOAT_IS_INF, UNITY_FLOAT_IS_NAN, UNITY_FLOAT_IS_NEG_INF, UNITY_FLOAT_IS_NOT_DET, UNITY_FLOAT_IS_NOT_INF, UNITY_FLOAT_IS_NOT_NAN, UNITY_FLOAT_IS_NOT_NEG_INF, UnityAddMsgIfSpecified, UnityPrint, UnityPrintFloat, UnityStrDet, UnityStrExpected, UnityStrInf, UnityStrInvalidFloatTrait, UnityStrNaN, UnityStrNegInf, UnityStrNot, UnityStrWas, UnityTestResultsFailBegin.
void UnityAssertDoublesWithin(const UNITY_DOUBLE delta, const UNITY_DOUBLE expected, const UNITY_DOUBLE actual, const char *msg, const UNITY_UINT lineNumber)
References RETURN_IF_FAIL_OR_IGNORE, UNITY_FAIL_AND_BAIL, UNITY_PRINT_EXPECTED_AND_ACTUAL_FLOAT, UnityAddMsgIfSpecified, UnityDoublesWithin, UnityTestResultsFailBegin.
void UnityAssertEqualDoubleArray(const UNITY_DOUBLE *expected, const UNITY_DOUBLE *actual, const UNITY_UINT32 num_elements, const char *msg, const UNITY_UINT lineNumber, const UNITY_FLAGS_T flags)
References RETURN_IF_FAIL_OR_IGNORE, UNITY_ARRAY_TO_ARRAY, UNITY_DOUBLE_PRECISION, UNITY_FAIL_AND_BAIL, UNITY_INTERNAL_PTR, UNITY_PRINT_EXPECTED_AND_ACTUAL_FLOAT, UNITY_PTR_ATTRIBUTE, UnityAddMsgIfSpecified, UnityDoublesWithin, UnityIsOneArrayNull, UnityPrint, UnityPrintNumberUnsigned, UnityPrintPointlessAndBail, UnityStrElement, UnityTestResultsFailBegin.
void UnityAssertDoubleSpecial(const UNITY_DOUBLE actual, const char *msg, const UNITY_UINT lineNumber, const UNITY_FLOAT_TRAIT_T style)
References isinf, isnan, RETURN_IF_FAIL_OR_IGNORE, UNITY_FAIL_AND_BAIL, UNITY_FLOAT_IS_DET, UNITY_FLOAT_IS_INF, UNITY_FLOAT_IS_NAN, UNITY_FLOAT_IS_NEG_INF, UNITY_FLOAT_IS_NOT_DET, UNITY_FLOAT_IS_NOT_INF, UNITY_FLOAT_IS_NOT_NAN, UNITY_FLOAT_IS_NOT_NEG_INF, UnityAddMsgIfSpecified, UnityPrint, UnityPrintFloat, UnityStrDet, UnityStrExpected, UnityStrInf, UnityStrInvalidFloatTrait, UnityStrNaN, UnityStrNegInf, UnityStrNot, UnityStrWas, UnityTestResultsFailBegin.
const void* UnityNumToPtr(const UNITY_INT num, const UNITY_UINT8 size)
References size, UNITY_INTERNAL_PTR, UnityQuickCompare.
const void* UnityFloatToPtr(const float num)
References UNITY_INTERNAL_PTR, UnityQuickCompare.
const void* UnityDoubleToPtr(const double num)
References UNITY_INTERNAL_PTR, UnityQuickCompare.