unity.h
UNITY
TEST_FAIL_MESSAGE
TEST_FAIL
TEST_IGNORE_MESSAGE
TEST_IGNORE
TEST_ONLY
TEST_PASS
TEST_FILE
TEST_ASSERT
TEST_ASSERT_TRUE
TEST_ASSERT_UNLESS
TEST_ASSERT_FALSE
TEST_ASSERT_NULL
TEST_ASSERT_NOT_NULL
TEST_ASSERT_EQUAL_INT
TEST_ASSERT_EQUAL_INT8
TEST_ASSERT_EQUAL_INT16
TEST_ASSERT_EQUAL_INT32
TEST_ASSERT_EQUAL_INT64
TEST_ASSERT_EQUAL
TEST_ASSERT_NOT_EQUAL
TEST_ASSERT_EQUAL_UINT
TEST_ASSERT_EQUAL_UINT8
TEST_ASSERT_EQUAL_UINT16
TEST_ASSERT_EQUAL_UINT32
TEST_ASSERT_EQUAL_UINT64
TEST_ASSERT_EQUAL_HEX
TEST_ASSERT_EQUAL_HEX8
TEST_ASSERT_EQUAL_HEX16
TEST_ASSERT_EQUAL_HEX32
TEST_ASSERT_EQUAL_HEX64
TEST_ASSERT_BITS
TEST_ASSERT_BITS_HIGH
TEST_ASSERT_BITS_LOW
TEST_ASSERT_BIT_HIGH
TEST_ASSERT_BIT_LOW
TEST_ASSERT_GREATER_THAN
TEST_ASSERT_GREATER_THAN_INT
TEST_ASSERT_GREATER_THAN_INT8
TEST_ASSERT_GREATER_THAN_INT16
TEST_ASSERT_GREATER_THAN_INT32
TEST_ASSERT_GREATER_THAN_INT64
TEST_ASSERT_GREATER_THAN_UINT
TEST_ASSERT_GREATER_THAN_UINT8
TEST_ASSERT_GREATER_THAN_UINT16
TEST_ASSERT_GREATER_THAN_UINT32
TEST_ASSERT_GREATER_THAN_UINT64
TEST_ASSERT_GREATER_THAN_HEX8
TEST_ASSERT_GREATER_THAN_HEX16
TEST_ASSERT_GREATER_THAN_HEX32
TEST_ASSERT_GREATER_THAN_HEX64
TEST_ASSERT_LESS_THAN
TEST_ASSERT_LESS_THAN_INT
TEST_ASSERT_LESS_THAN_INT8
TEST_ASSERT_LESS_THAN_INT16
TEST_ASSERT_LESS_THAN_INT32
TEST_ASSERT_LESS_THAN_INT64
TEST_ASSERT_LESS_THAN_UINT
TEST_ASSERT_LESS_THAN_UINT8
TEST_ASSERT_LESS_THAN_UINT16
TEST_ASSERT_LESS_THAN_UINT32
TEST_ASSERT_LESS_THAN_UINT64
TEST_ASSERT_LESS_THAN_HEX8
TEST_ASSERT_LESS_THAN_HEX16
TEST_ASSERT_LESS_THAN_HEX32
TEST_ASSERT_LESS_THAN_HEX64
TEST_ASSERT_GREATER_OR_EQUAL
TEST_ASSERT_GREATER_OR_EQUAL_INT
TEST_ASSERT_GREATER_OR_EQUAL_INT8
TEST_ASSERT_GREATER_OR_EQUAL_INT16
TEST_ASSERT_GREATER_OR_EQUAL_INT32
TEST_ASSERT_GREATER_OR_EQUAL_INT64
TEST_ASSERT_GREATER_OR_EQUAL_UINT
TEST_ASSERT_GREATER_OR_EQUAL_UINT8
TEST_ASSERT_GREATER_OR_EQUAL_UINT16
TEST_ASSERT_GREATER_OR_EQUAL_UINT32
TEST_ASSERT_GREATER_OR_EQUAL_UINT64
TEST_ASSERT_GREATER_OR_EQUAL_HEX8
TEST_ASSERT_GREATER_OR_EQUAL_HEX16
TEST_ASSERT_GREATER_OR_EQUAL_HEX32
TEST_ASSERT_GREATER_OR_EQUAL_HEX64
TEST_ASSERT_LESS_OR_EQUAL
TEST_ASSERT_LESS_OR_EQUAL_INT
TEST_ASSERT_LESS_OR_EQUAL_INT8
TEST_ASSERT_LESS_OR_EQUAL_INT16
TEST_ASSERT_LESS_OR_EQUAL_INT32
TEST_ASSERT_LESS_OR_EQUAL_INT64
TEST_ASSERT_LESS_OR_EQUAL_UINT
TEST_ASSERT_LESS_OR_EQUAL_UINT8
TEST_ASSERT_LESS_OR_EQUAL_UINT16
TEST_ASSERT_LESS_OR_EQUAL_UINT32
TEST_ASSERT_LESS_OR_EQUAL_UINT64
TEST_ASSERT_LESS_OR_EQUAL_HEX8
TEST_ASSERT_LESS_OR_EQUAL_HEX16
TEST_ASSERT_LESS_OR_EQUAL_HEX32
TEST_ASSERT_LESS_OR_EQUAL_HEX64
TEST_ASSERT_INT_WITHIN
TEST_ASSERT_INT8_WITHIN
TEST_ASSERT_INT16_WITHIN
TEST_ASSERT_INT32_WITHIN
TEST_ASSERT_INT64_WITHIN
TEST_ASSERT_UINT_WITHIN
TEST_ASSERT_UINT8_WITHIN
TEST_ASSERT_UINT16_WITHIN
TEST_ASSERT_UINT32_WITHIN
TEST_ASSERT_UINT64_WITHIN
TEST_ASSERT_HEX_WITHIN
TEST_ASSERT_HEX8_WITHIN
TEST_ASSERT_HEX16_WITHIN
TEST_ASSERT_HEX32_WITHIN
TEST_ASSERT_HEX64_WITHIN
TEST_ASSERT_EQUAL_PTR
TEST_ASSERT_EQUAL_STRING
TEST_ASSERT_EQUAL_STRING_LEN
TEST_ASSERT_EQUAL_MEMORY
TEST_ASSERT_EQUAL_INT_ARRAY
TEST_ASSERT_EQUAL_INT8_ARRAY
TEST_ASSERT_EQUAL_INT16_ARRAY
TEST_ASSERT_EQUAL_INT32_ARRAY
TEST_ASSERT_EQUAL_INT64_ARRAY
TEST_ASSERT_EQUAL_UINT_ARRAY
TEST_ASSERT_EQUAL_UINT8_ARRAY
TEST_ASSERT_EQUAL_UINT16_ARRAY
TEST_ASSERT_EQUAL_UINT32_ARRAY
TEST_ASSERT_EQUAL_UINT64_ARRAY
TEST_ASSERT_EQUAL_HEX_ARRAY
TEST_ASSERT_EQUAL_HEX8_ARRAY
TEST_ASSERT_EQUAL_HEX16_ARRAY
TEST_ASSERT_EQUAL_HEX32_ARRAY
TEST_ASSERT_EQUAL_HEX64_ARRAY
TEST_ASSERT_EQUAL_PTR_ARRAY
TEST_ASSERT_EQUAL_STRING_ARRAY
TEST_ASSERT_EQUAL_MEMORY_ARRAY
TEST_ASSERT_EACH_EQUAL_INT
TEST_ASSERT_EACH_EQUAL_INT8
TEST_ASSERT_EACH_EQUAL_INT16
TEST_ASSERT_EACH_EQUAL_INT32
TEST_ASSERT_EACH_EQUAL_INT64
TEST_ASSERT_EACH_EQUAL_UINT
TEST_ASSERT_EACH_EQUAL_UINT8
TEST_ASSERT_EACH_EQUAL_UINT16
TEST_ASSERT_EACH_EQUAL_UINT32
TEST_ASSERT_EACH_EQUAL_UINT64
TEST_ASSERT_EACH_EQUAL_HEX
TEST_ASSERT_EACH_EQUAL_HEX8
TEST_ASSERT_EACH_EQUAL_HEX16
TEST_ASSERT_EACH_EQUAL_HEX32
TEST_ASSERT_EACH_EQUAL_HEX64
TEST_ASSERT_EACH_EQUAL_PTR
TEST_ASSERT_EACH_EQUAL_STRING
TEST_ASSERT_EACH_EQUAL_MEMORY
TEST_ASSERT_FLOAT_WITHIN
TEST_ASSERT_EQUAL_FLOAT
TEST_ASSERT_EQUAL_FLOAT_ARRAY
TEST_ASSERT_EACH_EQUAL_FLOAT
TEST_ASSERT_FLOAT_IS_INF
TEST_ASSERT_FLOAT_IS_NEG_INF
TEST_ASSERT_FLOAT_IS_NAN
TEST_ASSERT_FLOAT_IS_DETERMINATE
TEST_ASSERT_FLOAT_IS_NOT_INF
TEST_ASSERT_FLOAT_IS_NOT_NEG_INF
TEST_ASSERT_FLOAT_IS_NOT_NAN
TEST_ASSERT_FLOAT_IS_NOT_DETERMINATE
TEST_ASSERT_DOUBLE_WITHIN
TEST_ASSERT_EQUAL_DOUBLE
TEST_ASSERT_EQUAL_DOUBLE_ARRAY
TEST_ASSERT_EACH_EQUAL_DOUBLE
TEST_ASSERT_DOUBLE_IS_INF
TEST_ASSERT_DOUBLE_IS_NEG_INF
TEST_ASSERT_DOUBLE_IS_NAN
TEST_ASSERT_DOUBLE_IS_DETERMINATE
TEST_ASSERT_DOUBLE_IS_NOT_INF
TEST_ASSERT_DOUBLE_IS_NOT_NEG_INF
TEST_ASSERT_DOUBLE_IS_NOT_NAN
TEST_ASSERT_DOUBLE_IS_NOT_DETERMINATE
TEST_ASSERT_MESSAGE
TEST_ASSERT_TRUE_MESSAGE
TEST_ASSERT_UNLESS_MESSAGE
TEST_ASSERT_FALSE_MESSAGE
TEST_ASSERT_NULL_MESSAGE
TEST_ASSERT_NOT_NULL_MESSAGE
TEST_ASSERT_EQUAL_INT_MESSAGE
TEST_ASSERT_EQUAL_INT8_MESSAGE
TEST_ASSERT_EQUAL_INT16_MESSAGE
TEST_ASSERT_EQUAL_INT32_MESSAGE
TEST_ASSERT_EQUAL_INT64_MESSAGE
TEST_ASSERT_EQUAL_MESSAGE
TEST_ASSERT_NOT_EQUAL_MESSAGE
TEST_ASSERT_EQUAL_UINT_MESSAGE
TEST_ASSERT_EQUAL_UINT8_MESSAGE
TEST_ASSERT_EQUAL_UINT16_MESSAGE
TEST_ASSERT_EQUAL_UINT32_MESSAGE
TEST_ASSERT_EQUAL_UINT64_MESSAGE
TEST_ASSERT_EQUAL_HEX_MESSAGE
TEST_ASSERT_EQUAL_HEX8_MESSAGE
TEST_ASSERT_EQUAL_HEX16_MESSAGE
TEST_ASSERT_EQUAL_HEX32_MESSAGE
TEST_ASSERT_EQUAL_HEX64_MESSAGE
TEST_ASSERT_BITS_MESSAGE
TEST_ASSERT_BITS_HIGH_MESSAGE
TEST_ASSERT_BITS_LOW_MESSAGE
TEST_ASSERT_BIT_HIGH_MESSAGE
TEST_ASSERT_BIT_LOW_MESSAGE
TEST_ASSERT_GREATER_THAN_MESSAGE
TEST_ASSERT_GREATER_THAN_INT_MESSAGE
TEST_ASSERT_GREATER_THAN_INT8_MESSAGE
TEST_ASSERT_GREATER_THAN_INT16_MESSAGE
TEST_ASSERT_GREATER_THAN_INT32_MESSAGE
TEST_ASSERT_GREATER_THAN_INT64_MESSAGE
TEST_ASSERT_GREATER_THAN_UINT_MESSAGE
TEST_ASSERT_GREATER_THAN_UINT8_MESSAGE
TEST_ASSERT_GREATER_THAN_UINT16_MESSAGE
TEST_ASSERT_GREATER_THAN_UINT32_MESSAGE
TEST_ASSERT_GREATER_THAN_UINT64_MESSAGE
TEST_ASSERT_GREATER_THAN_HEX8_MESSAGE
TEST_ASSERT_GREATER_THAN_HEX16_MESSAGE
TEST_ASSERT_GREATER_THAN_HEX32_MESSAGE
TEST_ASSERT_GREATER_THAN_HEX64_MESSAGE
TEST_ASSERT_LESS_THAN_MESSAGE
TEST_ASSERT_LESS_THAN_INT_MESSAGE
TEST_ASSERT_LESS_THAN_INT8_MESSAGE
TEST_ASSERT_LESS_THAN_INT16_MESSAGE
TEST_ASSERT_LESS_THAN_INT32_MESSAGE
TEST_ASSERT_LESS_THAN_INT64_MESSAGE
TEST_ASSERT_LESS_THAN_UINT_MESSAGE
TEST_ASSERT_LESS_THAN_UINT8_MESSAGE
TEST_ASSERT_LESS_THAN_UINT16_MESSAGE
TEST_ASSERT_LESS_THAN_UINT32_MESSAGE
TEST_ASSERT_LESS_THAN_UINT64_MESSAGE
TEST_ASSERT_LESS_THAN_HEX8_MESSAGE
TEST_ASSERT_LESS_THAN_HEX16_MESSAGE
TEST_ASSERT_LESS_THAN_HEX32_MESSAGE
TEST_ASSERT_LESS_THAN_HEX64_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_INT_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_INT8_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_INT16_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_INT32_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_INT64_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_UINT_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_UINT8_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_UINT16_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_UINT32_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_UINT64_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_HEX8_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_HEX16_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_HEX32_MESSAGE
TEST_ASSERT_GREATER_OR_EQUAL_HEX64_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_INT_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_INT8_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_INT16_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_INT32_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_INT64_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_UINT_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_UINT8_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_UINT16_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_UINT32_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_UINT64_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_HEX8_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_HEX16_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_HEX32_MESSAGE
TEST_ASSERT_LESS_OR_EQUAL_HEX64_MESSAGE
TEST_ASSERT_INT_WITHIN_MESSAGE
TEST_ASSERT_INT8_WITHIN_MESSAGE
TEST_ASSERT_INT16_WITHIN_MESSAGE
TEST_ASSERT_INT32_WITHIN_MESSAGE
TEST_ASSERT_INT64_WITHIN_MESSAGE
TEST_ASSERT_UINT_WITHIN_MESSAGE
TEST_ASSERT_UINT8_WITHIN_MESSAGE
TEST_ASSERT_UINT16_WITHIN_MESSAGE
TEST_ASSERT_UINT32_WITHIN_MESSAGE
TEST_ASSERT_UINT64_WITHIN_MESSAGE
TEST_ASSERT_HEX_WITHIN_MESSAGE
TEST_ASSERT_HEX8_WITHIN_MESSAGE
TEST_ASSERT_HEX16_WITHIN_MESSAGE
TEST_ASSERT_HEX32_WITHIN_MESSAGE
TEST_ASSERT_HEX64_WITHIN_MESSAGE
TEST_ASSERT_EQUAL_PTR_MESSAGE
TEST_ASSERT_EQUAL_STRING_MESSAGE
TEST_ASSERT_EQUAL_STRING_LEN_MESSAGE
TEST_ASSERT_EQUAL_MEMORY_MESSAGE
TEST_ASSERT_EQUAL_INT_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_INT8_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_INT16_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_INT32_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_INT64_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_UINT_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_UINT16_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_UINT32_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_UINT64_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_HEX_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_HEX8_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_HEX16_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_HEX32_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_HEX64_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_PTR_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_STRING_ARRAY_MESSAGE
TEST_ASSERT_EQUAL_MEMORY_ARRAY_MESSAGE
TEST_ASSERT_EACH_EQUAL_INT_MESSAGE
TEST_ASSERT_EACH_EQUAL_INT8_MESSAGE
TEST_ASSERT_EACH_EQUAL_INT16_MESSAGE
TEST_ASSERT_EACH_EQUAL_INT32_MESSAGE
TEST_ASSERT_EACH_EQUAL_INT64_MESSAGE
TEST_ASSERT_EACH_EQUAL_UINT_MESSAGE
TEST_ASSERT_EACH_EQUAL_UINT8_MESSAGE
TEST_ASSERT_EACH_EQUAL_UINT16_MESSAGE
TEST_ASSERT_EACH_EQUAL_UINT32_MESSAGE
TEST_ASSERT_EACH_EQUAL_UINT64_MESSAGE
TEST_ASSERT_EACH_EQUAL_HEX_MESSAGE
TEST_ASSERT_EACH_EQUAL_HEX8_MESSAGE
TEST_ASSERT_EACH_EQUAL_HEX16_MESSAGE
TEST_ASSERT_EACH_EQUAL_HEX32_MESSAGE
TEST_ASSERT_EACH_EQUAL_HEX64_MESSAGE
TEST_ASSERT_EACH_EQUAL_PTR_MESSAGE
TEST_ASSERT_EACH_EQUAL_STRING_MESSAGE
TEST_ASSERT_EACH_EQUAL_MEMORY_MESSAGE
TEST_ASSERT_FLOAT_WITHIN_MESSAGE
TEST_ASSERT_EQUAL_FLOAT_MESSAGE
TEST_ASSERT_EQUAL_FLOAT_ARRAY_MESSAGE
TEST_ASSERT_EACH_EQUAL_FLOAT_MESSAGE
TEST_ASSERT_FLOAT_IS_INF_MESSAGE
TEST_ASSERT_FLOAT_IS_NEG_INF_MESSAGE
TEST_ASSERT_FLOAT_IS_NAN_MESSAGE
TEST_ASSERT_FLOAT_IS_DETERMINATE_MESSAGE
TEST_ASSERT_FLOAT_IS_NOT_INF_MESSAGE
TEST_ASSERT_FLOAT_IS_NOT_NEG_INF_MESSAGE
TEST_ASSERT_FLOAT_IS_NOT_NAN_MESSAGE
TEST_ASSERT_FLOAT_IS_NOT_DETERMINATE_MESSAGE
TEST_ASSERT_DOUBLE_WITHIN_MESSAGE
TEST_ASSERT_EQUAL_DOUBLE_MESSAGE
TEST_ASSERT_EQUAL_DOUBLE_ARRAY_MESSAGE
TEST_ASSERT_EACH_EQUAL_DOUBLE_MESSAGE
TEST_ASSERT_DOUBLE_IS_INF_MESSAGE
TEST_ASSERT_DOUBLE_IS_NEG_INF_MESSAGE
TEST_ASSERT_DOUBLE_IS_NAN_MESSAGE
TEST_ASSERT_DOUBLE_IS_DETERMINATE_MESSAGE
TEST_ASSERT_DOUBLE_IS_NOT_INF_MESSAGE
TEST_ASSERT_DOUBLE_IS_NOT_NEG_INF_MESSAGE
TEST_ASSERT_DOUBLE_IS_NOT_NAN_MESSAGE
TEST_ASSERT_DOUBLE_IS_NOT_DETERMINATE_MESSAGE
void setUp(void)
References Counter.
Referenced by resetTest, UnityDefaultTestRun.
void tearDown(void)
Referenced by resetTest, UnityDefaultTestRun.
void suiteSetUp(void)
int suiteTearDown(int num_failures)