unity_fixture.h
TEST_GROUP
TEST_SETUP
TEST_TEAR_DOWN
TEST
IGNORE_TEST
RUN_TEST_CASE
TEST_GROUP_RUNNER
RUN_TEST_GROUP
UT_PTR_SET
TEST_ASSERT_POINTERS_EQUAL
TEST_ASSERT_BYTES_EQUAL
FAIL
CHECK
LONGS_EQUAL
STRCMP_EQUAL
DOUBLES_EQUAL
int UnityMain(int argc, const char *argv[], void(*runAllTests)(void))
References announceTestRun, UNITY_FIXTURE_T::RepeatCount, runAllTests, UNITY_STORAGE_T::TestFailures, Unity, UNITY_PRINT_EOL, UnityBegin, UnityEnd, UnityFixture, UnityGetCommandLineOptions, UNITY_FIXTURE_T::Verbose.
Referenced by main, TEST.
void UnityMalloc_MakeMallocFailAfterCount(int count)
References malloc_fail_countdown.
Referenced by TEST.